import * as vscode from "vscode";
import { CommandContext } from "../../../context/commandContext.js";

export const QUICKSTART_FLAG_KEY = "dvQuickRun.hasSeenQuickStart";

function buildEnvironmentSection(hasActiveEnvironment: boolean): string {
  if (hasActiveEnvironment) {
    return [
      "## Environment",
      "✅ Active Dataverse environment detected and ready.",
      "You can run the samples below straight away.",
      ""
    ].join("\n");
  }

  return [
    "## Environment",
    "1. Open the Command Palette",
    '2. Run: DV Quick Run: Add Environment',
    '3. Come back here and click "Run Query" above one of the examples below',
    ""
  ].join("\n");
}

export function buildQuickStartContent(hasActiveEnvironment: boolean): string {
  return [
    "# Welcome to DV Quick Run",
    "",
    "Run and explore Dataverse queries directly inside VS Code.",
    "",
    buildEnvironmentSection(hasActiveEnvironment),
    "## Build Queries Incrementally",
    "",
    "Think of your query as a canvas, not a finished string.",
    "",
    "Start simple, then refine step-by-step using guided suggestions:",
    "",
    "contacts",
    "→ + $top",
    "→ + $select",
    "→ refine filters",
    "",
    "DV Quick Run helps you refine queries incrementally instead of writing everything upfront.",
    "",
    "DV Quick Run becomes useful when you have a query in the editor.",
    'This page gives you runnable samples so CodeLens can appear naturally above each query.',
    "",
    "## DV Quick Run Hub",
    "",
    "Use the Hub when you want to see where your current investigation is and continue without losing context.",
    "",
    "Open it any time from the Command Palette:",
    "DV Quick Run: Open Hub",
    "",
    "## Access Context",
    "",
    "Access Context helps you inspect bounded operational participation for users, application users, teams, roles, and business units.",
    "",
    "Use it when you need to understand who or what participates operationally without treating DVQR as RBAC simulation or security administration tooling.",
    "",
    "You can:",
    "- inspect direct and inherited role participation",
    "- review team, role, application-user, and business-unit participation evidence",
    "- search the evidence locally inside the Access Context surface",
    "- export evidence for review or handoff",
    "",
    "Open it from the Command Palette:",
    "DV Quick Run: Investigate Access Context",
    "",
    "From Result Viewer rows, look for contextual actions such as Check User Access Context, Check Team Access Context, Check Role Access Context, Check Application User Context, or Check Business Unit Context when matching identity columns are present.",
    "",
    "## Capability Explorer",
    "",
    "Capability Explorer helps you discover executable Custom APIs and Functions available in the current Dataverse environment.",
    "",
    "You can:",
    "- inspect Custom API metadata and parameter readiness",
    "- validate whether Functions are exposed through OData metadata",
    "- preview execution requests before running them",
    "- safely execute eligible GET-style Functions",
    "- review structured execution diagnostics and response payloads",
    "",
    "Open it from the Command Palette:",
    "DV Quick Run: Open Capability Explorer",
    "",
    "The Hub shows whether your Result Viewer context is active, recoverable, historical, or stale.",
    "It also helps you reopen a closed Result Viewer and keeps investigation context isolated when you switch environments.",
    "",
    "## Investigation Continuity",
    "",
    "Queries, Result Viewer, Execution Insights, Operational Profiles, Access Context, Snapshot Library, Cross-Diff, and Timeline Reconstruction are designed to work together.",
    "",
    "A typical investigation starts with a query, continues through runtime or operational context, and only moves into snapshots, comparison, timeline reconstruction, or reconstruction artifacts when evidence preservation is required.",
    "",
    "DV Quick Run stays evidence-first throughout the investigation lifecycle.",
    "",
    "## Evidence Workspace, Snapshots, Diff & Timeline",
    "",
    "After you understand a table or record, use Snapshot Library when you need evidence you can compare, revisit, audit-enrich, or hand off.",
    "",
    "Typical investigation flow:",
    "capture snapshots → compare drift → reconstruct timeline → check audit evidence → export reconstruction artifacts",
    "",
    "Use it when you need to:",
    "- compare DEV, UAT, SIT, or PROD evidence without treating drift as deployment authority",
    "- understand when changes first appeared across 3+ same-environment snapshots",
    "- enrich findings with snapshot-bounded audit evidence where available",
    "- generate DVAF/DVIM reconstruction artifacts for eligible source-side metadata and identity participation drift findings",
    "- preserve HTML/PDF investigation handoff reports in the DV ForgeLab workspace",
    "",
    "Open it from the Command Palette:",
    "DV Quick Run: Open Snapshot Library",
    "",
    "Workspace layout:",
    ".dvforgelab/dvqr/snapshots",
    ".dvforgelab/dvqr/reports",
    ".dvforgelab/dvaf/exports • .dvforgelab/dvim/exports",
    "",
    "Boundary:",
    "DVQR investigates observed evidence and exports reconstruction intent. DVAF owns preview/apply and humans retain operational authority.",
    "",
    "## Run your first query",
    '👉 Click "Run Query" above this line',
    "contacts",
    "",
    "💡 Tip: Try starting simple — DV Quick Run will suggest adding $top, $select, or next steps as you go.",
    "",
    "## Try Query-by-Canvas",
    "",
    "1. Run the query above (`contacts`)",
    "2. Look for suggestions (e.g. add $top, $select)",
    "3. Preview and apply changes",
    "4. Re-run and refine further",
    "",
    "Workflow:",
    "detect → preview → apply → rerun",
    "",
    "## Try Snapshot Library after a useful query",
    "",
    "Once you find an entity worth investigating, capture an Operational Profile snapshot for later comparison.",
    "",
    "Try this flow:",
    "1. Open Snapshot Library",
    "2. Capture a snapshot for an entity such as account or contact",
    "3. Capture another snapshot after a change or from another environment",
    "4. Select exactly 2 snapshots for Cross-Diff, or 3+ compatible same-environment snapshots for Timeline Reconstruction",
    "5. Export reports or DVAF/DVIM reconstruction artifacts where supported",
    "",
    "Safety: snapshots and reports are evidence artifacts, not remediation instructions.",
    "",
    "## Try Explain",
    '👉 Click "Explain" above this line',
    "contacts?$select=fullname,emailaddress1&$top=5",
    "",
    "## Try an expand",
    "contacts?$select=fullname&$expand=parentcustomerid_account($select=name)&$top=5",
    "",
    "## Try a filtered query",
    "contacts?$select=fullname,emailaddress1&$filter=contains(fullname,'a')&$top=5",
    "",
    "## Try FetchXML",
    '👉 Click "Run FetchXML" above the <fetch line',
    "<fetch top=\"5\">",
    "  <entity name=\"account\">",
    "    <attribute name=\"name\" />",
    "    <attribute name=\"accountnumber\" />",
    "  </entity>",
    "</fetch>",
    "",
    "## Explore relationships (Advanced)",
    "",
    "👉 Try: DV Quick Run: Guided Traversal (Command Palette or editor right-click)",
    "",
    "Example traversal:",
    "account → contact → systemuser",
    "",
    "This helps you navigate across related tables step-by-step without writing complex queries.",
    "",
    "## Run queries as $batch",
    "",
    "After building and exploring queries, you can run them together using `$batch`.",
    "",
    "This is useful when you want to:",
    "- run several related queries in one go",
    "- test or validate multiple endpoints",
    "- execute queries more efficiently than separate calls",
    "",
    "### Try running multiple queries",
    "",
    "👉 Write two queries:",
    "",
    "contacts?$select=fullname&$top=5",
    "",
    "accounts?$select=name&$top=5",
    "",
    "👉 Select both queries and run:",
    "DV Quick Run: Run as $batch",
    "",
    "You will see:",
    "- each query result separately",
    "- a combined execution summary",
    "",
    "### Run traversal as $batch",
    "",
    "After completing a Guided Traversal, you can replay the full route using `$batch`.",
    "",
    "👉 Try this:",
    "",
    "1. Run a Guided Traversal (e.g. account → contact → systemuser)",
    "2. Complete the traversal",
    "3. Look for the suggestion:",
    "   💡 This traversal is ready to run as $batch",
    "4. Click it to execute all steps in a single request",
    "",
    "💡 Tip: If available, you can also refine the `$batch` before running it again.",
    "",
    "## Other useful features",
    "- Result Viewer: inspect and refine queries (Query-by-Canvas surface)",
    "- Investigate Record: inspect a record from GUID / JSON / logs",
    "- Guided Traversal: navigate between related tables step-by-step",
    "- Metadata Hover: get field hints directly in the editor",
    "- Capability Explorer: discover, preview, validate, and execute supported Dataverse Custom API capabilities",
    "- Access Context: inspect bounded operational participation for users, application users, teams, roles, and business units",
    "- Execution Insights: understand plugin, async operation, workflow, and Power Automate execution context",
    "- Operational Profiles: explore operational activity and investigation context around entities and records",
    "- Snapshot Library: capture, select, compare, and replay evidence snapshots",
    "- Cross-Environment Diff: compare two environment snapshots without treating drift as deployment authority",
    "- Timeline Reconstruction: reconstruct first-observed drift windows across 3+ same-environment snapshots",
    "- Audit Evidence Enrichment: add snapshot-bounded audit context where Dataverse audit rows are available",
    "- Reconstruction Artifacts: export DVAF handoff artifacts from eligible source-side metadata drift",
    "",
    "## Tips",
    "- CodeLens actions appear above supported queries",
    "- Ctrl+Enter runs the query under your cursor",
    "- You can reopen this page any time with: DV Quick Run: Open Quickstart",
    "",
    "If you do not see actions above the sample queries:",
    "- make sure DV Quick Run CodeLens is enabled",
    "- make sure your environment is configured",
    "- click inside a sample query line and try Ctrl+Enter",
    ""
  ].join("\n");
}

export async function runOpenQuickStartAction(ctx: CommandContext): Promise<void> {
  const hasActiveEnvironment = !!ctx.envContext.getActiveEnvironment();
  const document = await vscode.workspace.openTextDocument({
    content: buildQuickStartContent(hasActiveEnvironment),
    language: "plaintext"
  });

  await vscode.window.showTextDocument(document, { preview: false });
}

export async function hasSeenQuickStart(ctx: CommandContext): Promise<boolean> {
  return ctx.ext.globalState.get<boolean>(QUICKSTART_FLAG_KEY, false);
}

export async function markQuickStartSeen(ctx: CommandContext): Promise<void> {
  await ctx.ext.globalState.update(QUICKSTART_FLAG_KEY, true);
}
