import type { ComparisonDriftGroup, ComparisonViewModel } from "../../../core/comparison/index.js";
import { flattenReportFindings, type BuildComparisonReportOptions, type ComparisonReportChartModel, type ComparisonReportExecutiveSummary, type ComparisonReportKind, type ComparisonReportModel, type ComparisonReportProviderDistributionItem } from "./comparisonReportTypes.js";

function buildWatermarkFooter(): string {
  return "Generated by DV Quick Run. DVQR observes operational drift and supports verification; humans retain operational authority.";
}

function buildProviderDistribution(groups: readonly ComparisonDriftGroup[]): readonly ComparisonReportProviderDistributionItem[] {
  return groups
    .map((group) => ({
      label: group.title,
      count: group.differences.length
    }))
    .filter((item) => item.count > 0)
    .sort((left, right) => {
      const countDelta = right.count - left.count;
      if (countDelta !== 0) {
        return countDelta;
      }

      return left.label.localeCompare(right.label);
    });
}

function buildCharts(model: ComparisonViewModel): ComparisonReportChartModel {
  return {
    significanceDistribution: {
      high: model.summary.highCount,
      medium: model.summary.mediumCount,
      low: model.summary.lowCount
    },
    providerDistribution: buildProviderDistribution(model.groups)
  };
}

function buildDiffFindingsExecutiveSummary(model: ComparisonViewModel): ComparisonReportExecutiveSummary {
  const differenceCount = model.summary.differenceCount;
  const providerCount = model.summary.providerCount;
  const highCount = model.summary.highCount;
  const subject = model.summary.subjectLabel ? ` for ${model.summary.subjectLabel}` : "";

  if (differenceCount === 0) {
    return {
      heading: "Executive Summary",
      paragraphs: [
        `DVQR did not observe evidence-backed operational drift${subject} across the selected comparison providers.`,
        "This should be treated as quiet comparison evidence only. It does not certify operational parity beyond the supplied snapshots and provider coverage."
      ],
      highlights: [
        "No evidence-backed operational differences were returned by the selected providers.",
        "Snapshot and provider coverage should still be considered before assuming deployment equivalence."
      ]
    };
  }

  const strongestGroups = buildProviderDistribution(model.groups).slice(0, 3).map((item) => item.label);
  const concentration = strongestGroups.length > 0
    ? `The strongest operational signals were concentrated in ${strongestGroups.join(", ")}.`
    : "The observed operational signals should be reviewed by significance and provider context.";

  return {
    heading: "Executive Summary",
    paragraphs: [
      `${differenceCount} evidence-backed operational difference${differenceCount === 1 ? " was" : "s were"} observed across ${providerCount} comparison provider${providerCount === 1 ? "" : "s"}${subject}.`,
      `${highCount} high-significance operational signal${highCount === 1 ? " was" : "s were"} identified. ${concentration}`,
      "Observed differences should be treated as operational investigation context and externally verified before deployment equivalence is assumed."
    ],
    highlights: [
      `${highCount} high-significance signal${highCount === 1 ? "" : "s"}`,
      `${model.summary.mediumCount} medium-significance signal${model.summary.mediumCount === 1 ? "" : "s"}`,
      `${model.summary.lowCount} low-significance signal${model.summary.lowCount === 1 ? "" : "s"}`
    ]
  };
}

function buildInvestigationHandoffExecutiveSummary(model: ComparisonViewModel): ComparisonReportExecutiveSummary {
  const differenceCount = model.summary.differenceCount;
  const highCount = model.summary.highCount;
  const subject = model.summary.subjectLabel ? ` for ${model.summary.subjectLabel}` : "";

  if (differenceCount === 0) {
    return {
      heading: "Executive Handoff Summary",
      paragraphs: [
        `This handoff package preserves a quiet comparison result${subject}. No evidence-backed operational drift was returned by the selected providers.`,
        "Follow-on review should still consider snapshot trust, provider coverage, and external deployment context before assuming operational equivalence."
      ],
      highlights: [
        "No unresolved drift findings were rendered from this comparison.",
        "Use this package as investigation continuity, not certification."
      ]
    };
  }

  return {
    heading: "Executive Handoff Summary",
    paragraphs: [
      `This handoff package preserves investigation continuity for ${differenceCount} observed operational drift signal${differenceCount === 1 ? "" : "s"}${subject}.`,
      `${highCount} high-significance operational difference${highCount === 1 ? " requires" : "s require"} external validation before operational equivalence should be assumed.`,
      "The package is intended to help another reviewer or team continue the investigation with source/target context, snapshot trust, grouped evidence, and verification boundaries intact."
    ],
    highlights: [
      "Preserves comparison context and grouped evidence for follow-on review.",
      "Focuses reviewer attention on unresolved operational verification.",
      "Does not approve, certify, or remediate observed drift."
    ]
  };
}

function buildExecutiveSummary(kind: ComparisonReportKind, model: ComparisonViewModel): ComparisonReportExecutiveSummary {
  return kind === "DiffFindingsSummary"
    ? buildDiffFindingsExecutiveSummary(model)
    : buildInvestigationHandoffExecutiveSummary(model);
}

export function buildComparisonReportModel(
  kind: ComparisonReportKind,
  model: ComparisonViewModel,
  options: BuildComparisonReportOptions = {}
): ComparisonReportModel {
  const generatedAt = options.generatedAt ?? new Date();
  const topFindings = flattenReportFindings(model.groups);
  const reportTitle = kind === "DiffFindingsSummary"
    ? `Diff Findings Summary: ${model.summary.sourceLabel} → ${model.summary.targetLabel}`
    : `Investigation Handoff: ${model.summary.sourceLabel} → ${model.summary.targetLabel}`;

  return {
    kind,
    title: reportTitle,
    generatedAtIso: generatedAt.toISOString(),
    sourceLabel: model.summary.sourceLabel,
    targetLabel: model.summary.targetLabel,
    subjectLabel: model.summary.subjectLabel,
    sourceCapturedAtIso: model.summary.sourceCapturedAtIso,
    targetCapturedAtIso: model.summary.targetCapturedAtIso,
    snapshotTrust: model.snapshotTrust,
    highCount: model.summary.highCount,
    mediumCount: model.summary.mediumCount,
    lowCount: model.summary.lowCount,
    providerCount: model.summary.providerCount,
    differenceCount: model.summary.differenceCount,
    executiveSummary: buildExecutiveSummary(kind, model),
    charts: kind === "DiffFindingsSummary" ? buildCharts(model) : undefined,
    topFindings: topFindings.slice(0, kind === "DiffFindingsSummary" ? 6 : 20),
    groups: model.groups.map((group) => ({
      id: group.id,
      title: group.title,
      summary: group.summary,
      significance: group.significance,
      differenceCount: group.differences.length,
      differences: group.differences
    })),
    sourceModel: model,
    watermark: {
      logoDataUri: options.watermarkLogoDataUri,
      footerText: buildWatermarkFooter()
    }
  };
}
