import assert from "assert";
import { renderComparisonReportPdf } from "../../product/comparison/reports/comparisonReportPdfRenderer.js";
import type { ComparisonReportModel } from "../../product/comparison/reports/comparisonReportTypes.js";

function createReport(): ComparisonReportModel {
  return {
    kind: "DiffFindingsSummary",
    title: "Diff Findings Summary: Source → Target",
    generatedAtIso: "2026-06-01T00:00:00.000Z",
    sourceLabel: "Source",
    targetLabel: "Target",
    subjectLabel: "Account",
    highCount: 1,
    mediumCount: 0,
    lowCount: 0,
    differenceCount: 1,
    providerCount: 1,
    sourceCapturedAtIso: "2026-06-01T00:00:00.000Z",
    targetCapturedAtIso: "2026-06-01T00:00:00.000Z",
    snapshotTrust: {
      sourceTrustState: "Verified",
      targetTrustState: "Verified"
    },
    executiveSummary: {
      heading: "Executive Summary",
      paragraphs: ["One evidence-backed operational difference was observed."],
      highlights: ["1 high-significance signal"]
    },
    charts: {
      significanceDistribution: {
        high: 1,
        medium: 0,
        low: 0
      },
      providerDistribution: [
        {
          label: "Plugin Step Runtime Behaviour Drift",
          count: 1
        }
      ]
    },
    topFindings: [
      {
        id: "finding-1",
        title: "Plugin state changed",
        summary: "Observed plugin step registration metadata differs across snapshots.",
        groupTitle: "Plugin Step Runtime Behaviour Drift",
        kind: "Changed",
        significance: "High",
        evidenceCount: 1
      }
    ],
    groups: [],
    sourceModel: {
      title: "Diff Findings Summary: Source → Target",
      summary: {
        sourceLabel: "Source",
        targetLabel: "Target",
        sourceCapturedAtIso: "2026-06-01T00:00:00.000Z",
        targetCapturedAtIso: "2026-06-01T00:00:00.000Z",
        highCount: 1,
        mediumCount: 0,
        lowCount: 0,
        providerCount: 1,
        differenceCount: 1,
        subjectLabel: "Account"
      },
      snapshotTrust: {
        sourceTrustState: "Verified",
        targetTrustState: "Verified"
      },
      groups: [],
      providerResults: []
    },
    watermark: {
      logoDataUri: undefined,
      footerText: "Generated by DV Quick Run. DVQR observes operational drift and supports verification; humans retain operational authority."
    }
  };
}

suite("comparisonReportPdfRenderer pagination", () => {
  test("renders a PDF without creating obvious footer-only duplicate pages", async () => {
    const pdf = await renderComparisonReportPdf(createReport());
    const text = pdf.toString("latin1");

    assert.ok(text.includes("/Type /Page"));
    assert.ok(pdf.length > 1000);
  });
});
