import { DvqrMcpLiveCapabilityPolicy, DVQR_MCP_COMMERCIAL_BOUNDARY } from "./mcpLiveCapabilityPolicy.js";
import { DVQR_LIVE_MCP_TOOLS } from "./mcpLiveToolCatalogue.js";

export function createDvqrMcpCapabilityPayload(proEnabled: boolean) {
  const policy = new DvqrMcpLiveCapabilityPolicy(proEnabled);
  return {
    contractVersion: "dvqr-mcp-capabilities-v1",
    product: "DV Quick Run",
    releaseVersion: "0.15.6",
    transport: "stdio",
    mode: "local-read-only",
    commercialBoundary: DVQR_MCP_COMMERCIAL_BOUNDARY,
    proEnabled,
    implementedTools: policy.projectAll(DVQR_LIVE_MCP_TOOLS),
    toolSelectionGuidance: {
      investigations: [
        "PRIMARY ENTRY: whenever the user asks to investigate or troubleshoot a Dataverse record, table, relationship, missing record, unexpected behaviour, readiness issue, evidence gap, Mini RCA or root-cause question, call dvqr_start_investigation first. Do not search for a different entry point.",
        "Canonical investigation workflow: 1) dvqr_start_investigation exactly once (automatically performs Preparation and Bootstrap), 2) present the Investigation Brief, 3) on a subsequent explicit user confirmation preserve the SAME investigationId and confirm with dvqr_confirm_investigation_intent; if that tool is not exposed by the host, use dvqr_continue_investigation with confirmationText as the canonical fallback. Never call dvqr_start_investigation again for confirmation/continuation. Persist genuinely edited intent with dvqr_update_investigation_intent, 4) dvqr_continue_investigation, 5) acquire the exact strategy-selected bounded evidence provider, 6) dvqr_assess_investigation_readiness, 7) generate the first Mini RCA checkpoint using the exact recommendedAction returned by continuation (normally dvqr_generate_mini_rca_checkpoint, which aliases the same canonical generator). Only after that checkpoint may managed Record follow-ons such as mechanism-context or timeline-context run. For Record investigations that explicitly follow the post-checkpoint mechanism question: 8) acquire one bounded mechanism-context item, 9) reassess readiness because the evidence fingerprint changed, 10) explicitly regenerate Mini RCA if the investigator wants a refreshed frozen checkpoint. Steps 9-10 reuse persisted evidence and never recollect Dataverse evidence.",
        "Confirmation trust boundary: confirmationText is supplied by the MCP host and DVQR cannot independently authenticate it against the conversation transcript. The host must never synthesize Confirm/Yes/Continue wording, infer confirmation from skip/assume/automatic-continuation requests, or call the confirmation tool without an explicit immediately preceding user confirmation. DVQR's confirmation classifier is defence-in-depth, not trusted message provenance.",
        "HOST ORCHESTRATION GUARD: while a Record investigation remains pending inferred-intent confirmation, repeated dvqr_start_investigation calls for the same transient record ID are suppressed within the MCP session; the transient ID may come from structured subject.recordId or the canonical Dataverse GUID resolved from the opening question and return the original prepared response rather than creating another investigation. Independently of in-memory pending state, guarded continuation/evidence/readiness/Mini-RCA actions are rejected when the persisted investigation journal shows bootstrap completed but currentIntent is absent. This prevents host retries, tool-surface churn, or agent orchestration from silently bypassing the intent gate.",
        "For continue or advance investigation requests, call dvqr_continue_investigation. It is the only tool that advances persisted strategy state, and it reconciles persisted provider evidence before presenting the first incomplete step.",
        "dvqr_get_investigation and dvqr_get_investigation_strategy are read-only and must never be described as continuing or advancing an investigation. Persisted truth access: prefer dvqr_get_investigation for the full investigation document. If an optimized host does not expose it, dvqr_get_investigation_strategy is the authoritative fallback and includes managedVerification, managedCompletionHistory, managedReadiness, managedMiniRcaCheckpoint, currentIntent, miniRcaArtifactRefs and stateConsistency from the same persisted journal. Never substitute focus suggestions, strategy-only inference, old assistant prose or conversational memory for these truth fields.",
        "For show readiness for investigation ID, call dvqr_get_investigation_readiness with only investigationId.",
        "Do not use dvqr_get_investigation_gaps for conversational persisted-investigation readiness requests; it is a low-level readiness-engine operation requiring a canonical request.",
        "Metadata, relationship-context, runtime-relationship, business-path-runtime and mechanism-context providers persist investigation-owned evidence. Provider mappings are provider-level contributions, not canonical readiness. When a concrete Record target is persisted, only business-path-runtime completes the target-aware runtime strategy step; legacy runtime-relationship evidence may remain useful journal evidence but must not advance that step. Persisting mechanism-context after the first Mini RCA marks managed readiness stale until dvqr_assess_investigation_readiness is called again. Standalone Operational Anchors exploration is not automatically attached to an investigation.",
        "FAILED PREREQUISITE RECOVERY: when managed continuation reports blockedPrerequisite, do not automatically repeat the same failed/unavailable provider. Preserve the current strategy gate, explain the failed boundary, and ask for or act on a material recovery change such as corrected subject binding or changed environment/access. A later explicit retry is valid only after that boundary changes; a reused failed evidence item is not progress.",
        "MECHANISM TOOLCALL HANDOFF: after the first Mini RCA checkpoint, both investigationPlan.recommendedNextAction and dvqr_continue_investigation must converge on a real public MCP action. Prefer dvqr_acquire_mechanism_context (first-class alias) or the canonical dvqr_acquire_investigation_evidence with providerId=mechanism-context. Never emit or execute dvqr_acquire_mechanism_evidence as a public tool name; it is an abstract strategy capability only. The tool call must carry the persisted target and require explicit fromIso/toIso host inputs.",
        "POST-CHECKPOINT REFRESH CONTRACT: after the first Mini RCA checkpoint, mechanism-context requires the persisted target plus an explicit justified fromIso/toIso window. Persisting new mechanism-context evidence makes managed readiness stale and makes the current Mini RCA checkpoint stale against the new evidence fingerprint. The authoritative next action is readiness reassessment without Dataverse recollection; only after that succeeds may an explicit new Mini RCA checkpoint be generated. Preserve prior Mini RCA artifacts as historical frozen checkpoints rather than mutating or replacing them.",
        "TEMPORAL BOUNDARY PROVENANCE: mechanism-context and timeline-context require fromIso, toIso, and boundaryRequestText copied from the user's current temporal instruction. The instruction may be absolute (explicit ISO values) or relative (for example 'last 30 days'); relative requests may be resolved deterministically by the host, but DVQR must record them as UserRelativeBoundary rather than pretending the resolved ISO values were supplied verbatim. If the user supplied no temporal instruction, the host must not invent one.",
        "PERSISTED QA FACTS: dvqr_get_investigation returns managedVerification derived from the persisted journal, readiness and checkpoint fingerprints. Use managedVerification for final YES/NO acceptance summaries; do not reconstruct acceptance facts from conversational memory, prior assistant prose, or assumed tool history. Pass 10.9.3 also exposes managedVerification.stateConsistency with an explicit isConsistent verdict and named invariant violations; hosts must report any violation instead of silently reconciling contradictory fields.",
        "COMPLETION / CONVERGENCE: when every deterministic strategy step is Completed or Skipped and the latest Mini RCA checkpoint matches the current non-stale managed readiness fingerprint, dvqr_continue_investigation returns completion.state=InvestigationComplete with no recommendedAction. Treat this as an authoritative stop signal. Repeated Continue Investigation is idempotent and must not reacquire evidence, reassess readiness, or regenerate Mini RCA. optionalActions may still be presented as explicit investigator choices and do not make deterministic completion false.",
        "HOST-SURFACE MINI RCA FALLBACK: if continuation recommends dvqr_generate_mini_rca_checkpoint/dvqr_generate_mini_rca but the host did not expose that dedicated generator, do not substitute dvqr_get_mini_rca. After explicit user authorization, call dvqr_continue_investigation on the same investigationId with executeRecommendedMiniRca=true. DVQR rechecks the canonical recommendation and executes only Mini RCA generation; every non-Mini-RCA action is rejected.",
        "POST-COMPLETION TIMELINE RECONVERGENCE: completion history is immutable. A completion milestone is persisted as soon as Mini RCA generation itself creates a fully converged deterministic checkpoint; an extra Continue Investigation turn is not required merely to record history. After any persisted completion milestone, managedVerification.deterministicStrategyComplete is monotonic: optional evidence may reopen a synthesis-refresh step and make currentlyComplete=false, but it does not make the already-completed deterministic strategy false. If a previously completed investigation explicitly acquires optional Timeline evidence, current completion may become false because readiness/checkpoint are stale while everReachedCompletion remains true. Only when the exact next action is readiness reassessment may dvqr_continue_investigation perform the journal-only readiness fallback internally; it must acquire no Dataverse evidence and must return the next explicit action rather than auto-generating Mini RCA.",
        "STRATEGY ACTION CONTRACT: every executable Record investigation step must surface recommendedAction.kind=ToolCall. Treat recommendedAction.tool as the public MCP action and recommendedAction.arguments as persisted-safe arguments. If requiredHostArguments is present, resolve those transient values only from the named current user/conversation boundary (for example the raw source record GUID from the opening request), pass them to the exact tool, and do not persist them merely for orchestration. presentedStep.capability is an abstract strategy capability and must never be treated as a public MCP tool name. Do not semantically search for a similar tool, replace a generator with a getter, or claim the exact action is unavailable before attempting that public tool.",
        "RECOMMENDED-ACTION INTEGRITY: deterministic recommendedAction responses carry integrity.contractVersion=dvqr-managed-recommended-action-integrity-v1 and a stable actionId derived from investigationId, current strategy step, exact public tool, persisted-safe arguments and the current evidence fingerprint. Treat that actionId as the identity of the one action DVQR selected for this boundary. Execute exactly one explicit tool call, do not alter persisted-safe arguments such as providerId or targetTable, add only requiredHostArguments explicitly specified by DVQR, then STOP and return to persisted DVQR state/continuation before any second managed action. A changed evidence set, strategy step, tool or arguments yields a different actionId.",
        "RECOMMENDED-ACTION EXECUTION ENFORCEMENT: for deterministic evidence acquisition, managed readiness, and Mini RCA checkpoint generation, integrity.actionId is now the required execution token. The live dispatcher re-derives the current canonical recommendation from persisted state before execution and rejects missing, stale, replayed, tool-substituted, provider-substituted, target-substituted, or otherwise altered requests with RecommendedActionAuthorizationRequired / RecommendedActionIntegrityViolation. A confirmation response does not itself authorize the next evidence action: return through dvqr_continue_investigation to obtain the current actionId. One successful deterministic execution consumes that state boundary because persisted evidence/strategy changes make the old actionId stale.",
        "ACTION TOKEN NON-DISCLOSURE: RecommendedActionAuthorizationRequired and RecommendedActionIntegrityViolation must not disclose the current actionable actionId. Only an explicit dvqr_continue_investigation response may issue the current recommendedAction.integrity.actionId. Authorization failures return nextRequiredAction=dvqr_continue_investigation so an optimized host cannot self-authorize by retrying a prematurely attempted action with a token learned from the error.",
        "MANAGED READINESS ROUTING: the public live MCP readiness action is dvqr_assess_investigation_readiness with investigationId only. The host must call that tool directly when the strategy reaches readiness; do not substitute contributor availability, stored-readiness retrieval, or a guessed low-level request envelope. A successful managed readiness assessment persists the checkpoint required by dvqr_generate_mini_rca.",
        "TIMELINE CONTEXT: for managed Record investigations, timeline-context is an optional post-first-Mini-RCA discriminator, not a mandatory strategy gate and not a way to leapfrog readiness or the first checkpoint merely because the opening question mentions chronology. When deterministic mechanism/plugin steps are complete and no Timeline evidence exists, dvqr_continue_investigation may expose Timeline under optionalActions rather than recommendedAction. Execute it only after an explicit user branch choice. Use dvqr_acquire_timeline_context or dvqr_acquire_investigation_evidence with providerId timeline-context with the persisted target and an explicit justified fromIso/toIso boundary. Reuse a prior mechanism window only when the investigator explicitly chooses or confirms that same boundary; never widen or invent a window to obtain more events. Persisting Timeline evidence stales managed readiness and the current Mini RCA checkpoint, so the next deterministic actions are readiness reassessment and explicit checkpoint regeneration without reacquiring evidence. Never substitute plugin-execution-understanding for Timeline or vice versa. Timeline normalizes bounded Audit, AsyncOperation and PluginTrace observations into one ordered investigation ledger; ObservedBefore/ObservedAfter, adjacency and temporal proximity are sequence evidence only and never establish triggering, causality, root cause, success, failure or exclusive ownership. Empty remains bounded absence-of-observation and Unavailable remains indeterminate.",
        "MECHANISM FALSE-PREMISE RESPONSE RULE: when a user asks the host to confirm a proposition that contradicts persisted mechanism evidence or an interpretationBoundary, reject the proposition before explaining it. The first semantic response must be an explicit correction such as 'No. That conclusion is not supported.' Never begin with agreement words such as Correct, Yes, Confirmed or Exactly when the proposition says Empty means no plug-in/workflow ran, Unavailable means no audit/event occurred, or Observed proves causality. Empty is a successful bounded zero-match observation; Unavailable is not a zero-row result because the source was not successfully read; Observed establishes bounded participation only. Do not repeat or paraphrase the false proposition as established fact."
      ],
      businessPaths: [
        "Use dvqr_discover_business_paths when the question is about likely multi-hop business flow between two Dataverse tables; it ranks only metadata-verified candidates and performs no record query.",
        "VERIFY SAVED PATHS: when the user says verify/re-verify a saved Business Path, call dvqr_verify_business_path exactly once. That one call already performs current metadata revalidation, exact bounded runtime execution, and verification refresh. Do not call dvqr_revalidate_business_path before/after it and do not also call dvqr_test_business_path in the same user request. Use dvqr_revalidate_business_path only for metadata-only questions.",
        "EMPTY-FRONTIER / NO-BROADENING RULE: when dvqr_test_business_path or dvqr_verify_business_path returns zero rows, NoContinuationObserved, or target-not-reached, that scoped Business Path operation is complete. Do not automatically follow it with dvqr_execute_odata, dvqr_probe_relationship_path, dvqr_discover_business_paths, a broad target-table query, alternate route discovery, target-concept expansion, metadata search for substitute targets, an alternate entity-set guess, or any other widened fallback in the same user request. A broader or alternate investigation requires a new explicit user request.",
        "EVIDENCE WORDING: Preferred means workspace guidance and verified means bounded historical runtime evidence. Never call a Business Path production-ready, guaranteed, causal, universally valid, or organisation-wide truth from those signals alone.",

        "When the user explicitly names or selects a business traversal table sequence, preserve that sequence as assertedBusinessPathTables when calling dvqr_validate_business_paths. Do not replace the asserted sequence with a shorter route merely because the shorter route returns rows.",
        "When exact relationship schema variants for the asserted traversal are known, pass them in assertedBusinessPathRelationshipSchemaNames so DVQR tests the exact relationship identity rather than a semantically different variant such as Author versus Patient.",
        "Use dvqr_validate_business_paths when a real sourceRecordId is available and the user wants to test an asserted or discovered business traversal. Inspect promotionDecision: only promotionDecision.eligible=true authorizes the exact asserted traversal as a save candidate.",
        "When promotionDecision.eligible=true, DVQR returns saveFollowUp with a short-lived promotionAuthorizationId. Present the returned question to the user and STOP. Do not save automatically in the same turn.",
        "On a subsequent explicit user confirmation such as 'Yes, save it', call dvqr_save_business_path with promotionAuthorizationId and confirmSave=true. A name is optional in authorized mode; use the returned suggestedName unless the user supplies another name. Do not reconstruct intendedTables, hops or relationship identities from conversation; the server-held authorization is authoritative and single-use.",
        "runtimePreferredPath is bounded reachability evidence for the supplied record. It is never a substitute for an asserted Business Path. If it differs from the asserted traversal, present it separately as an observed/runtime alternative and require a new explicit user selection before saving it.",
        "Manual dvqr_save_business_path remains available only for explicitly reviewed routes without a promotion authorization. Manual mode requires sourceTable, targetTable, intendedTables and exact hops and remains not-runtime-verified.",
        "Use dvqr_find_relationship_paths when the question is specifically about relationship shape, navigation properties, or shortest metadata paths rather than business-flow likelihood.",
        "A Pass 10.1 business-path candidate is metadata-valid only. Never describe it as runtime-viable or business-preferred until bounded hop-by-hop runtime evidence exists. Pass 10.2 runtime preference is source-record-specific evidence, not persistent organisational truth.",
        "Do not interpret an empty direct relationship as proof that the downstream business record is missing; a multi-hop business path may still exist."
      ],
      customApis: [
        "If the user asks what a named Custom API does, asks to explain it, or asks why or when to use it, call dvqr_explain_custom_api.",
        "If the user asks for the exact definition, parameters, response properties or metadata call scaffold of one named Custom API, call dvqr_get_custom_api_definition.",
        "Never substitute dvqr_get_custom_api_definition for an explanation or practical-usage request.",
        "If the user asks to compare two or more named Custom APIs, call dvqr_compare_custom_apis rather than calling Explain repeatedly.",
        "If the user asks which individual Custom API or APIs fit a capability and does not ask for a design or ordered workflow, call dvqr_recommend_custom_apis.",
        "If the user asks to design, architect, assemble, sequence, improve, review or compare an architecture, solution, workflow, pipeline, stage order, alternatives or multi-API design, call dvqr_recommend_solution_architecture directly.",
        "For architecture requests, do not call dvqr_recommend_custom_apis first and do not manually assemble a design from shortlist or definition results.",
        "Pass the user's original architecture goal unchanged. Do not broaden unsupported domain or technology terms into adjacent supported concepts.",
        "Recommendation honours explicit exclusions, reports confidence and may return no strong fit rather than promoting weak lexical matches.",
        "Use dvqr_discover_custom_apis only for inventory, filtering and search.",
        "Before live Custom API execution, call dvqr_preview_custom_api_execution and review the exact short-lived, single-use preview session.",
        "Stop after preview and ask the user to reply exactly EXECUTE in a new message. Then call dvqr_execute_custom_api with the returned previewId. Preview sessions are short-lived, single-use, and cannot be replayed. Pass 2 executes public global generate-only Actions only.",
        "After a completed or failed Custom API execution, call dvqr_interpret_custom_api_execution to classify the outcome, analyse outputs and recommend evidence-backed next steps without re-executing or contacting Dataverse.",
        "Do not reconstruct Custom API definitions, comparisons or recommendations through dvqr_execute_odata, saved result files or terminal processing."
      ]
    },
    investigationWorkflow: {
      title: "Investigation",
      primaryEntryTool: "dvqr_start_investigation",
      steps: [
        { order: 1, action: "Start Investigation", tool: "dvqr_start_investigation", automaticResult: "Preparation + Bootstrap + Investigation Brief" },
        { order: 2, action: "Confirm or Edit Investigation Intent", tool: "dvqr_confirm_investigation_intent", alternativeTool: "dvqr_update_investigation_intent" },
        { order: 3, action: "Continue Investigation", tool: "dvqr_continue_investigation" },
        { order: 4, action: "Acquire Recommended Evidence", tool: "dvqr_acquire_investigation_evidence" },
        { order: 5, action: "Assess Readiness", tool: "dvqr_assess_investigation_readiness" },
        { order: 6, action: "Generate Mini RCA", tool: "dvqr_generate_mini_rca" },
        { order: 7, action: "Acquire Mechanism Context (optional post-checkpoint)", tool: "dvqr_acquire_investigation_evidence" },
        { order: 8, action: "Reassess Readiness After Mechanism Evidence", tool: "dvqr_assess_investigation_readiness" },
        { order: 9, action: "Regenerate Mini RCA (explicit)", tool: "dvqr_generate_mini_rca" }
      ],
      routingRule: "For any investigation request, call dvqr_start_investigation first unless the user supplied an existing investigationId and explicitly asked to continue or inspect it."
    },
    deferredCapabilities: [
      "FetchXML generation from verified paths",
      "Bound Custom API execution, Functions, complex parameters and mutation-capable operation execution",
      "Execution Profile projection",
      "DVQR Score projection",
      "Timeline, Cross-Environment Diff and Mini RCA orchestration"
    ],
    limitations: [
      "No PATCH, DELETE or workspace mutation tools are registered. POST is restricted to explicitly confirmed, short-lived single-use preview sessions for public global generate-only Custom API Actions.",
      "OData execution uses Azure CLI authentication and requires an explicit local Dataverse environment. Azure CLI authenticates Dataverse requests only; it does not grant or determine DVQR Pro entitlement.",
      "On Windows, low-level Node fetch failures retry through a bounded PowerShell transport using the same reviewed method, route and body.",
      "Pro readiness calls require DVQR_MCP_PRO_ENABLED=true until packaged entitlement reuse is connected."
    ]
  };
}
