import * as vscode from "vscode";

export interface MetadataAwareJsonPayloadField {
  name: string;
  type?: string;
  required?: boolean;
  description?: string;
  previewSupport?: string;
  trust?: string;
  source?: string;
  allowedValues?: Array<{ value: string | number | boolean; label: string }>;
  allowedValuesLabel?: string;
}

export interface MetadataAwareJsonPayloadEditorOptions {
  title: string;
  operationName: string;
  environmentName?: string;
  routePreview?: string;
  payloadJson: string;
  fields: MetadataAwareJsonPayloadField[];
  validatePayload?: (payloadJson: string) => string | undefined;
}

interface PayloadEditorMessage {
  type?: string;
  payloadJson?: string;
}

export async function openMetadataAwareJsonPayloadEditor(
  options: MetadataAwareJsonPayloadEditorOptions
): Promise<string | undefined> {
  const panel = vscode.window.createWebviewPanel(
    "dvQuickRunPayloadEditor",
    options.title,
    vscode.ViewColumn.Beside,
    {
      enableScripts: true,
      retainContextWhenHidden: true
    }
  );

  return await new Promise<string | undefined>((resolve) => {
    let resolved = false;

    const complete = (value: string | undefined): void => {
      if (resolved) {
        return;
      }
      resolved = true;
      resolve(value);
      panel.dispose();
    };

    panel.webview.html = renderPayloadEditorHtml(options);

    const subscription = panel.webview.onDidReceiveMessage((message: PayloadEditorMessage) => {
      if (message?.type === "cancel") {
        complete(undefined);
        return;
      }

      if (message?.type === "reset") {
        panel.webview.postMessage({ type: "resetPayload", payloadJson: options.payloadJson });
        return;
      }

      if (message?.type === "validate" && typeof message.payloadJson === "string") {
        const validationError = validatePayloadJson(message.payloadJson, options.validatePayload);
        void panel.webview.postMessage({ type: "validationResult", error: validationError });
        return;
      }

      if (message?.type === "apply" && typeof message.payloadJson === "string") {
        const validationError = validatePayloadJson(message.payloadJson, options.validatePayload);
        if (validationError) {
          void panel.webview.postMessage({ type: "validationResult", error: validationError });
          return;
        }
        complete(message.payloadJson);
      }
    });

    panel.onDidDispose(() => {
      subscription.dispose();
      complete(undefined);
    });
  });
}

function validatePayloadJson(
  payloadJson: string,
  validatePayload?: (payloadJson: string) => string | undefined
): string | undefined {
  if (!payloadJson.trim()) {
    return "Preview payload JSON is required.";
  }

  try {
    JSON.parse(payloadJson) as unknown;
  } catch (error) {
    return error instanceof Error ? error.message : String(error);
  }

  return validatePayload?.(payloadJson);
}

function renderPayloadEditorHtml(options: MetadataAwareJsonPayloadEditorOptions): string {
  const nonce = createNonce();
  const initialState = JSON.stringify({
    operationName: options.operationName,
    environmentName: options.environmentName?.trim() || "Unknown",
    routePreview: options.routePreview ?? "Preview route is generated by the calling surface.",
    payloadJson: options.payloadJson,
    fields: options.fields
  });

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}';">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(options.title)}</title>
  <style>
    :root {
      color-scheme: dark;
      --bg: var(--vscode-editor-background);
      --fg: var(--vscode-editor-foreground);
      --muted: var(--vscode-descriptionForeground);
      --border: var(--vscode-panel-border);
      --card: var(--vscode-sideBar-background);
      --input: var(--vscode-input-background);
      --error: var(--vscode-errorForeground);
      --ok: var(--vscode-testing-iconPassed);
      --button: var(--vscode-button-background);
      --buttonFg: var(--vscode-button-foreground);
    }
    body {
      margin: 0;
      padding: 18px;
      background: var(--bg);
      color: var(--fg);
      font-family: var(--vscode-font-family);
      font-size: var(--vscode-font-size);
    }
    .shell { display: grid; gap: 14px; }
    .header, .section {
      border: 1px solid var(--border);
      border-radius: 8px;
      background: var(--card);
    }
    .header { padding: 14px 16px; }
    h1 { margin: 0 0 6px; font-size: 18px; }
    .subtitle { color: var(--muted); }
    .section-title {
      padding: 10px 12px;
      border-bottom: 1px solid var(--border);
      font-weight: 700;
    }
    .section-body { padding: 12px; }
    pre.route {
      margin: 0;
      white-space: pre-wrap;
      overflow-wrap: anywhere;
      font-family: var(--vscode-editor-font-family);
      font-size: 12px;
    }
    textarea {
      width: 100%;
      min-height: 360px;
      box-sizing: border-box;
      resize: vertical;
      border: 1px solid var(--border);
      border-radius: 6px;
      padding: 12px;
      color: var(--fg);
      background: var(--input);
      font-family: var(--vscode-editor-font-family);
      font-size: var(--vscode-editor-font-size);
      line-height: 1.5;
    }
    .validation {
      margin-top: 10px;
      font-weight: 600;
    }
    .validation.ok { color: var(--ok); }
    .validation.error { color: var(--error); }
    .fields {
      display: grid;
      gap: 8px;
    }
    .field {
      display: grid;
      grid-template-columns: minmax(120px, 220px) minmax(0, 1fr);
      gap: 10px;
      padding: 8px;
      border: 1px solid var(--border);
      border-radius: 6px;
      align-items: start;
    }
    .field-name {
      font-weight: 700;
      min-width: 0;
      overflow-wrap: anywhere;
    }
    .field-meta {
      color: var(--muted);
      min-width: 0;
      overflow-wrap: anywhere;
    }
    .field-options {
      margin-top: 4px;
      color: var(--fg);
      opacity: 0.92;
    }
    .field-source {
      margin-top: 4px;
      color: var(--muted);
      font-size: 11px;
    }
    @media (max-width: 720px) {
      .field {
        grid-template-columns: 1fr;
      }
    }
    .actions {
      display: flex;
      justify-content: flex-end;
      gap: 8px;
      position: sticky;
      bottom: 0;
      padding: 12px 0 0;
      background: var(--bg);
    }
    button {
      border: 1px solid var(--border);
      border-radius: 5px;
      padding: 7px 12px;
      color: var(--buttonFg);
      background: var(--button);
      cursor: pointer;
    }
    button.secondary {
      color: var(--fg);
      background: transparent;
    }
    button:disabled {
      opacity: 0.55;
      cursor: not-allowed;
    }
  </style>
</head>
<body>
  <div class="shell">
    <header class="header">
      <h1>DV Quick Run — Preview Payload Editor</h1>
      <div class="subtitle" id="subtitle"></div>
    </header>

    <section class="section">
      <div class="section-title">Route</div>
      <div class="section-body"><pre class="route" id="route"></pre></div>
    </section>

    <section class="section">
      <div class="section-title">Editable JSON payload</div>
      <div class="section-body">
        <textarea id="payload" spellcheck="false" aria-label="Editable JSON payload"></textarea>
        <div class="validation" id="validation">Validating…</div>
      </div>
    </section>

    <section class="section">
      <div class="section-title">Parameter metadata</div>
      <div class="section-body"><div class="fields" id="fields"></div></div>
    </section>

    <div class="actions">
      <button class="secondary" id="reset">Reset Template</button>
      <button class="secondary" id="cancel">Cancel</button>
      <button id="apply">Apply to Preview</button>
    </div>
  </div>

  <script nonce="${nonce}">
    const vscode = acquireVsCodeApi();
    const state = ${initialState};
    const payload = document.getElementById('payload');
    const validation = document.getElementById('validation');
    const apply = document.getElementById('apply');

    document.getElementById('subtitle').textContent = state.operationName + ' · Preview only · Environment: ' + state.environmentName;
    document.getElementById('route').textContent = state.routePreview;
    payload.value = state.payloadJson;

    const fields = document.getElementById('fields');
    for (const field of state.fields) {
      const row = document.createElement('div');
      row.className = 'field';
      row.title = [
        field.name,
        'Type: ' + (field.type || 'Unknown'),
        'Required: ' + (field.required ? 'Yes' : 'No'),
        field.previewSupport ? 'Preview support: ' + field.previewSupport : '',
        field.trust ? 'Trust: ' + field.trust : '',
        field.description ? 'Description: ' + field.description : '',
        field.source ? 'Source: ' + field.source : '',
        Array.isArray(field.allowedValues) && field.allowedValues.length ? (field.allowedValuesLabel || 'Allowed values') + ': ' + field.allowedValues.map((option) => String(option.value) + ' = ' + option.label).join(', ') : ''
      ].filter(Boolean).join('\\n');

      const name = document.createElement('div');
      name.className = 'field-name';
      name.textContent = field.name;
      const meta = document.createElement('div');
      meta.className = 'field-meta';
      meta.textContent = (field.type || 'Unknown') + ' · ' + (field.required ? 'Required' : 'Optional') + (field.previewSupport ? ' · ' + field.previewSupport : '');
      if (Array.isArray(field.allowedValues) && field.allowedValues.length) {
        const options = document.createElement('div');
        options.className = 'field-options';
        options.textContent = (field.allowedValuesLabel || 'Allowed values') + ': ' + field.allowedValues.map((option) => String(option.value) + ' = ' + option.label).join(', ');
        meta.append(options);
      }
      if (field.source) {
        const source = document.createElement('div');
        source.className = 'field-source';
        source.textContent = field.source;
        meta.append(source);
      }
      row.append(name, meta);
      fields.append(row);
    }

    function localValidate() {
      try {
        JSON.parse(payload.value);
        validation.textContent = 'JSON syntax is valid. Apply will run metadata validation before updating the preview.';
        validation.className = 'validation ok';
        apply.disabled = false;
      } catch (error) {
        validation.textContent = 'Invalid JSON: ' + (error && error.message ? error.message : String(error));
        validation.className = 'validation error';
        apply.disabled = true;
      }
    }

    payload.addEventListener('input', localValidate);
    document.getElementById('reset').addEventListener('click', () => vscode.postMessage({ type: 'reset' }));
    document.getElementById('cancel').addEventListener('click', () => vscode.postMessage({ type: 'cancel' }));
    apply.addEventListener('click', () => vscode.postMessage({ type: 'apply', payloadJson: payload.value }));

    window.addEventListener('message', (event) => {
      const message = event.data;
      if (message.type === 'resetPayload') {
        payload.value = message.payloadJson;
        localValidate();
      }
      if (message.type === 'validationResult') {
        if (message.error) {
          validation.textContent = message.error;
          validation.className = 'validation error';
          apply.disabled = true;
        } else {
          validation.textContent = 'Payload is valid for preview.';
          validation.className = 'validation ok';
          apply.disabled = false;
        }
      }
    });

    localValidate();
  </script>
</body>
</html>`;
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function createNonce(): string {
  const alphabet = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
  let nonce = "";
  for (let i = 0; i < 32; i += 1) {
    nonce += alphabet.charAt(Math.floor(Math.random() * alphabet.length));
  }
  return nonce;
}
