import type { DvqrPromptDefinition } from "./promptLibraryTypes.js";

const tableParameter = {
  id: "table",
  label: "Table",
  description: "Dataverse table logical name.",
  placeholder: "account",
  required: true,
  example: "contact"
} as const;

const sourceTableParameter = { ...tableParameter, id: "sourceTable", label: "Source table", placeholder: "contact" } as const;
const targetTableParameter = { ...tableParameter, id: "targetTable", label: "Target table", placeholder: "task" } as const;
const recordIdParameter = {
  id: "recordId",
  label: "Record ID",
  description: "Canonical Dataverse record GUID.",
  placeholder: "00000000-0000-0000-0000-000000000000",
  required: true
} as const;
const apiParameter = {
  id: "apiName",
  label: "Custom API",
  description: "Exact Dataverse Custom API unique name.",
  placeholder: "contoso_ProcessRequest",
  required: true
} as const;
const investigationParameter = {
  id: "investigationId",
  label: "Investigation ID",
  description: "Persisted DVQR investigation ID.",
  placeholder: "inv-...",
  required: true
} as const;

export const DVQR_PROMPT_CATALOGUE: readonly DvqrPromptDefinition[] = [
  {
    id: "discover-capabilities",
    categoryId: "environment-understanding",
    journeyStage: "discover",
    title: "Show what DVQR can do",
    description: "Start with the implemented Free and Pro MCP capability surface.",
    template: "Show me what DV Quick Run can do through MCP, grouped into practical investigation workflows.",
    parameters: [],
    capabilityTool: "dvqr_list_capabilities",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_list_capabilities"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["search-metadata", "understand-business-capabilities", "profile-table", "start-investigation"],
    tags: ["capabilities", "getting-started", "discover"]
  },
  {
    id: "search-metadata",
    categoryId: "metadata-query",
    journeyStage: "discover",
    title: "Find tables for a concept",
    description: "Search Dataverse metadata without inventing EntityDefinitions filters.",
    template: "Find Dataverse tables related to {{concept}} and explain why the strongest matches are relevant.",
    parameters: [{ id: "concept", label: "Concept", description: "Business or Dataverse concept to search for.", placeholder: "customer service", required: true, example: "appointment" }],
    capabilityTool: "dvqr_search_metadata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_search_metadata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["inspect-table-metadata", "profile-table"],
    tags: ["metadata", "tables", "search"]
  },
  {
    id: "inspect-table-metadata",
    categoryId: "metadata-query",
    journeyStage: "understand",
    title: "Inspect one table",
    description: "Retrieve bounded entity-definition metadata for a known table.",
    template: "Show me the important metadata for the {{table}} table, including its primary ID, primary name, ownership and useful schema facts.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_entity_metadata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_entity_metadata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-table", "find-relationship-paths"],
    tags: ["metadata", "schema", "table"]
  },
  {
    id: "explain-odata",
    categoryId: "metadata-query",
    journeyStage: "understand",
    title: "Explain an OData query",
    description: "Understand query shape before execution.",
    template: "Explain this Dataverse OData query, including filters, selects, expands and likely result shape: {{query}}",
    parameters: [{ id: "query", label: "OData query", description: "Dataverse OData path or URL.", placeholder: "accounts?$select=name&$top=5", required: true }],
    capabilityTool: "dvqr_explain_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_explain_odata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["run-odata"],
    tags: ["odata", "explain", "query"]
  },
  {
    id: "run-odata",
    categoryId: "metadata-query",
    journeyStage: "query",
    title: "Run a bounded read-only query",
    description: "Execute one explicit OData GET against Dataverse.",
    template: "Run this read-only Dataverse query and summarize the returned rows without changing data: {{query}}",
    parameters: [{ id: "query", label: "OData query", description: "Dataverse OData GET path.", placeholder: "accounts?$select=accountid,name&$top=5", required: true }],
    capabilityTool: "dvqr_execute_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_execute_odata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["explain-odata", "find-relationship-paths"],
    tags: ["odata", "execute", "read-only"]
  },
  {
    id: "profile-table",
    categoryId: "operational-profile",
    journeyStage: "understand",
    title: "Get Operational Profile & DVQR Score",
    description: "Build the canonical live Operational Profile and calibrated DVQR Score.",
    template: "Get the current live Operational Profile and DVQR Score for {{table}}. Explain the weighted evidence and the final calibrated score without inventing hidden contributors.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-score-boundaries", "find-relationship-paths", "start-investigation"],
    tags: ["operational-profile", "dvqr-score", "density"]
  },
  {
    id: "profile-score-boundaries",
    categoryId: "operational-profile",
    journeyStage: "verify",
    title: "Interpret DVQR Score safely",
    description: "Test the canonical interpretation boundary around DVQR Score.",
    template: "For {{table}}, explain what the DVQR Score proves and what it does not prove about health, quality, security, performance, business value and root cause.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: ["profile-table"],
    followUpPromptIds: ["start-investigation"],
    tags: ["dvqr-score", "guardrails", "interpretation"]
  },
  {
    id: "explain-lookup",
    categoryId: "relationships-traversal",
    journeyStage: "understand",
    title: "Understand a lookup",
    description: "Explain lookup semantics without guessing target navigation.",
    template: "Explain the {{lookup}} lookup on {{table}}, including whether it is polymorphic and which target navigation properties are metadata-backed.",
    parameters: [tableParameter, { id: "lookup", label: "Lookup", description: "Lookup logical name.", placeholder: "parentcustomerid", required: true }],
    capabilityTool: "dvqr_explain_lookup",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_explain_lookup"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["find-relationship-paths"],
    tags: ["lookup", "polymorphic", "relationship"]
  },
  {
    id: "find-relationship-paths",
    categoryId: "relationships-traversal",
    journeyStage: "navigate",
    title: "Find metadata-valid relationship paths",
    description: "Find bounded metadata-valid routes between two tables.",
    template: "Find metadata-valid relationship paths from {{sourceTable}} to {{targetTable}}. Explain the route shapes without claiming runtime viability.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_find_relationship_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_find_relationship_paths"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["discover-business-paths", "probe-relationship-path"],
    tags: ["relationship", "path", "metadata"]
  },
  {
    id: "discover-business-paths",
    categoryId: "relationships-traversal",
    journeyStage: "navigate",
    title: "Discover likely business paths",
    description: "Rank depth-diverse metadata-backed candidate business routes.",
    template: "Discover likely business paths from {{sourceTable}} to {{targetTable}}. Keep metadata-valid, runtime-viable and business-preferred meanings separate.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_discover_business_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_business_paths"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["validate-business-paths", "start-investigation"],
    tags: ["business-path", "relationship", "ranking"]
  },
  {
    id: "validate-business-paths",
    categoryId: "relationships-traversal",
    journeyStage: "verify",
    title: "Validate business paths with runtime rows",
    description: "Execute bounded path validation and distinguish viable from empty paths.",
    template: "Using source record {{recordId}} on {{sourceTable}}, validate candidate business paths to {{targetTable}} hop by hop. Show where each path returns rows or becomes empty.",
    parameters: [sourceTableParameter, recordIdParameter, targetTableParameter],
    capabilityTool: "dvqr_validate_business_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_validate_business_paths"],
    prerequisitePromptIds: ["discover-business-paths"],
    followUpPromptIds: ["start-investigation"],
    tags: ["business-path", "runtime", "rows", "verify"]
  },
  {
    id: "probe-relationship-path",
    categoryId: "relationships-traversal",
    journeyStage: "verify",
    title: "Probe one relationship route",
    description: "Use bounded runtime reads to test one selected relationship route.",
    template: "Probe the selected relationship path from {{sourceTable}} record {{recordId}} toward {{targetTable}} and report only observed runtime reachability.",
    parameters: [sourceTableParameter, recordIdParameter, targetTableParameter],
    capabilityTool: "dvqr_probe_relationship_path",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_probe_relationship_path"],
    prerequisitePromptIds: ["find-relationship-paths"],
    followUpPromptIds: ["start-investigation"],
    tags: ["relationship", "probe", "runtime"]
  },
  {
    id: "discover-custom-apis",
    categoryId: "custom-apis",
    journeyStage: "discover",
    title: "Discover Custom APIs",
    description: "List or search public Custom APIs through the canonical metadata surface.",
    template: "Find public Dataverse Custom APIs related to {{goal}} and show the strongest metadata-backed matches.",
    parameters: [{ id: "goal", label: "Goal", description: "Capability or text to search for.", placeholder: "translate customer messages", required: true }],
    capabilityTool: "dvqr_discover_custom_apis",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_custom_apis"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["explain-custom-api", "recommend-custom-apis"],
    tags: ["custom-api", "discover", "metadata"]
  },
  {
    id: "explain-custom-api",
    categoryId: "custom-apis",
    journeyStage: "understand",
    title: "Explain a Custom API",
    description: "Explain purpose, binding, inputs, outputs and safe invocation shape.",
    template: "Explain what {{apiName}} does, when I would use it, its binding, inputs and outputs, and the execution safety boundary.",
    parameters: [apiParameter],
    capabilityTool: "dvqr_explain_custom_api",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_explain_custom_api"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["preview-custom-api", "compare-custom-apis"],
    tags: ["custom-api", "explain", "usage"]
  },
  {
    id: "compare-custom-apis",
    categoryId: "custom-apis",
    journeyStage: "understand",
    title: "Compare named Custom APIs",
    description: "Compare exact APIs from one deterministic metadata snapshot.",
    template: "Compare these exact Custom APIs and explain which is the better fit for my goal: {{apiNames}}",
    parameters: [{ id: "apiNames", label: "Custom APIs", description: "Comma-separated exact unique names.", placeholder: "contoso_Reply, contoso_Summarize", required: true }],
    capabilityTool: "dvqr_compare_custom_apis",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_compare_custom_apis"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["recommend-solution-architecture", "preview-custom-api"],
    tags: ["custom-api", "compare"]
  },
  {
    id: "recommend-custom-apis",
    categoryId: "custom-apis",
    journeyStage: "discover",
    title: "Recommend APIs for a goal",
    description: "Rank individual public Custom APIs without manufacturing an architecture.",
    template: "Which individual public Dataverse Custom APIs best fit this goal: {{goal}}? Return no strong fit rather than guessing.",
    parameters: [{ id: "goal", label: "Goal", description: "Natural-language capability goal.", placeholder: "draft customer replies", required: true }],
    capabilityTool: "dvqr_recommend_custom_apis",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_recommend_custom_apis"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["explain-custom-api", "recommend-solution-architecture"],
    tags: ["custom-api", "recommendation", "goal"]
  },
  {
    id: "recommend-solution-architecture",
    categoryId: "custom-apis",
    journeyStage: "understand",
    title: "Design a Custom API architecture",
    description: "Build an ordered metadata-backed multi-API architecture for a stated goal.",
    template: "Design an end-to-end Dataverse Custom API solution architecture for this goal without broadening unsupported requirements: {{goal}}",
    parameters: [{ id: "goal", label: "Architecture goal", description: "Original architecture or workflow goal.", placeholder: "multilingual customer-service triage", required: true }],
    capabilityTool: "dvqr_recommend_solution_architecture",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_recommend_solution_architecture"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["preview-custom-api"],
    tags: ["custom-api", "architecture", "workflow"]
  },
  {
    id: "preview-custom-api",
    categoryId: "custom-apis",
    journeyStage: "verify",
    title: "Preview Custom API execution",
    description: "Build the authoritative metadata-only invocation preview before execution.",
    template: "Preview execution of {{apiName}} with these proposed parameters, but do not execute it: {{parameters}}",
    parameters: [apiParameter, { id: "parameters", label: "Parameters", description: "Proposed scalar values in a readable form.", placeholder: "Text='hello'", required: true }],
    capabilityTool: "dvqr_preview_custom_api_execution",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_preview_custom_api_execution"],
    prerequisitePromptIds: ["explain-custom-api"],
    followUpPromptIds: [],
    tags: ["custom-api", "preview", "execution-safety"]
  },
  {
    id: "start-investigation",
    categoryId: "managed-investigation",
    journeyStage: "investigate",
    title: "Start a managed investigation",
    description: "Create a persisted Professional Investigation from the user's actual problem statement.",
    template: "Start a DVQR investigation for this problem: {{question}}",
    parameters: [{ id: "question", label: "Investigation question", description: "Problem statement, optionally including table and record GUID.", placeholder: "Why is the related task missing for this contact record?", required: true }],
    capabilityTool: "dvqr_start_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_start_investigation"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["show-investigation-strategy", "continue-investigation", "show-investigation-state"],
    tags: ["investigation", "pro", "persistent"]
  },
  {
    id: "show-investigation-state",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "Show persisted investigation state",
    description: "Reload the authoritative investigation state instead of reconstructing it conversationally.",
    template: "Show me the current persisted state, intent, evidence and next strategy step for investigation {{investigationId}} without advancing it.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-investigation-strategy", "continue-investigation", "show-readiness"],
    tags: ["investigation", "state", "read-only"]
  },
  {
    id: "continue-investigation",
    categoryId: "managed-investigation",
    journeyStage: "investigate",
    title: "Continue one managed step",
    description: "Advance exactly one canonical strategy boundary and return to persisted state.",
    template: "Continue investigation {{investigationId}} by exactly one canonical DVQR strategy step. Do not chain additional evidence or execution actions.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_continue_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_continue_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-investigation-state", "list-investigation-evidence", "show-readiness", "get-mini-rca"],
    tags: ["investigation", "continue", "strategy"]
  },
  {
    id: "show-readiness",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Assess investigation readiness",
    description: "Persist the canonical readiness assessment from current evidence.",
    template: "Assess and explain the current readiness for investigation {{investigationId}}. Do not recollect evidence as part of readiness assessment.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_assess_investigation_readiness",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_assess_investigation_readiness"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["get-mini-rca", "list-investigation-evidence", "continue-investigation"],
    tags: ["investigation", "readiness", "evidence"]
  },
  {
    id: "get-mini-rca",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Generate bounded Mini RCA",
    description: "Generate a persisted evidence-backed hypothesis checkpoint without claiming root cause.",
    template: "Generate the managed Mini RCA checkpoint for investigation {{investigationId}} using only current persisted evidence and readiness. Keep supported, weakened and unresolved hypotheses separate.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_generate_mini_rca",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_generate_mini_rca"],
    prerequisitePromptIds: ["show-readiness"],
    followUpPromptIds: ["show-investigation-strategy", "continue-investigation", "show-investigation-state"],
    tags: ["investigation", "mini-rca", "hypothesis"]
  },
  {
    id: "understand-business-capabilities",
    categoryId: "environment-understanding",
    journeyStage: "discover",
    title: "Find business capabilities and operational anchors",
    description: "Discover bounded metadata-backed business surfaces before choosing a traversal or investigation path.",
    template: "From {{sourceTable}}, discover the strongest Dataverse business capabilities and operational anchors. Separate governance, scheduling, coordination and execution roles, and do not claim runtime data exists.",
    parameters: [sourceTableParameter],
    capabilityTool: "dvqr_discover_operational_anchors",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_operational_anchors"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["find-relationship-paths", "discover-business-paths", "start-investigation"],
    tags: ["business-capability", "operational-anchor", "discover"]
  },
  {
    id: "resolve-navigation-property",
    categoryId: "relationships-traversal",
    journeyStage: "understand",
    title: "Resolve an exact navigation property",
    description: "Resolve metadata-verified navigation names before composing relationship queries.",
    template: "Resolve the exact Dataverse navigation property from {{sourceTable}} to {{targetTable}}. If my guessed property {{guessedProperty}} is wrong, show only metadata-verified alternatives and do not invent a navigation name.",
    parameters: [sourceTableParameter, targetTableParameter, { id: "guessedProperty", label: "Guessed property", description: "Optional navigation or lookup name to verify.", placeholder: "primarycontactid", required: false }],
    capabilityTool: "dvqr_resolve_navigation_property",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_resolve_navigation_property"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["generate-relationship-query", "find-relationship-paths"],
    tags: ["navigation-property", "metadata", "relationship"]
  },
  {
    id: "generate-relationship-query",
    categoryId: "relationships-traversal",
    journeyStage: "query",
    title: "Generate a verified relationship query",
    description: "Generate bounded OData only from a metadata-verified relationship route.",
    template: "Generate a bounded Dataverse OData query from {{sourceTable}} to {{targetTable}} using only a metadata-verified relationship path. If no exact route is verified, return no query rather than guessing.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_generate_relationship_query",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_generate_relationship_query"],
    prerequisitePromptIds: ["find-relationship-paths"],
    followUpPromptIds: ["run-odata", "probe-relationship-path"],
    tags: ["relationship", "odata", "query-generation"]
  },
  {
    id: "get-custom-api-definition",
    categoryId: "custom-apis",
    journeyStage: "understand",
    title: "Get the exact Custom API definition",
    description: "Retrieve factual binding, parameter and response metadata for one exact Custom API.",
    template: "Give me the exact metadata definition for {{apiName}}, including Action/Function kind, binding, inputs, outputs and metadata-only call scaffold. Do not substitute another operation.",
    parameters: [apiParameter],
    capabilityTool: "dvqr_get_custom_api_definition",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_custom_api_definition"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["check-custom-api-readiness", "preview-custom-api"],
    tags: ["custom-api", "definition", "metadata"]
  },
  {
    id: "check-custom-api-readiness",
    categoryId: "custom-apis",
    journeyStage: "verify",
    title: "Check Custom API execution readiness",
    description: "Run metadata-only pre-flight checks without executing the API.",
    template: "Check whether {{apiName}} is ready for safe DVQR invocation with these proposed parameters: {{parameters}}. Show blockers and warnings, but do not execute it.",
    parameters: [apiParameter, { id: "parameters", label: "Parameters", description: "Proposed scalar values for metadata-only validation.", placeholder: "Text='hello'", required: true }],
    capabilityTool: "dvqr_check_custom_api_execution",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_check_custom_api_execution"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["preview-custom-api"],
    tags: ["custom-api", "readiness", "preflight"]
  },
  {
    id: "interpret-custom-api-execution",
    categoryId: "custom-apis",
    journeyStage: "verify",
    title: "Interpret a Custom API execution",
    description: "Explain stored runtime evidence without re-executing the API.",
    template: "Interpret the most recent stored Custom API execution evidence. Explain what happened, returned outputs or failure class, and bounded next steps without executing anything again.",
    parameters: [],
    capabilityTool: "dvqr_interpret_custom_api_execution",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_interpret_custom_api_execution"],
    prerequisitePromptIds: [],
    followUpPromptIds: [],
    tags: ["custom-api", "execution", "interpret"]
  },
  {
    id: "show-investigation-strategy",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "Show the investigation strategy",
    description: "Inspect the authoritative persisted strategy without advancing it.",
    template: "Show the current canonical strategy for investigation {{investigationId}}, including completed, current and upcoming bounded steps. Do not advance or acquire evidence.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_investigation_strategy",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_investigation_strategy"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["continue-investigation", "acquire-recommended-evidence"],
    tags: ["investigation", "strategy", "plan"]
  },
  {
    id: "acquire-recommended-evidence",
    categoryId: "managed-investigation",
    journeyStage: "investigate",
    title: "Acquire exactly one recommended evidence item",
    description: "Execute only the current persisted evidence recommendation and stop after one provider result.",
    template: "For investigation {{investigationId}}, acquire exactly the current recommended DVQR evidence item using its exact persisted action token and provider. Persist that one bounded result, reconcile strategy, then stop.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_acquire_investigation_evidence",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_acquire_investigation_evidence"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["list-investigation-evidence", "show-readiness", "continue-investigation"],
    tags: ["investigation", "evidence", "acquire"]
  },
  {
    id: "list-investigation-evidence",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "List persisted investigation evidence",
    description: "Review the investigation-owned evidence set without recollecting anything.",
    template: "List the persisted evidence for investigation {{investigationId}}, grouped by provider and evidence state. Do not recollect or reinterpret missing evidence as zero.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_list_investigation_evidence",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_list_investigation_evidence"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-readiness", "summarize-investigation"],
    tags: ["investigation", "evidence", "list"]
  },
  {
    id: "summarize-investigation",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "Summarize the persisted investigation",
    description: "Summarize current state and evidence without reconstructing it from conversation memory.",
    template: "Summarize investigation {{investigationId}} from its persisted DVQR state: question, intent, evidence, strategy status, readiness and unresolved gaps. Do not acquire new evidence.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_summarize_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_summarize_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-investigation-strategy", "show-readiness", "get-mini-rca"],
    tags: ["investigation", "summary", "handoff"]
  },
  {
    id: "read-mini-rca",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Read the latest Mini RCA checkpoint",
    description: "Read the persisted checkpoint without regenerating or changing evidence.",
    template: "Show the latest persisted Mini RCA checkpoint for investigation {{investigationId}}. Keep supported, weakened and unresolved hypotheses distinct, and do not regenerate it.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_mini_rca",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_mini_rca"],
    prerequisitePromptIds: ["get-mini-rca"],
    followUpPromptIds: ["continue-investigation", "summarize-investigation"],
    tags: ["investigation", "mini-rca", "checkpoint", "read-only"]
  }
,
  {
    id: "find-customer-tables",
    categoryId: "environment-understanding",
    journeyStage: "discover",
    title: "Find the customer-facing tables",
    description: "Find metadata-backed tables around a customer concept before choosing a path.",
    template: "Find the strongest Dataverse tables related to {{concept}}. Group likely core, supporting and activity-oriented tables, and say when metadata alone cannot establish business importance.",
    parameters: [{ id: "concept", label: "Customer concept", description: "Business concept to search for.", placeholder: "customer", required: true }],
    capabilityTool: "dvqr_search_metadata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_search_metadata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["inspect-table-metadata", "understand-business-capabilities"],
    tags: ["environment", "metadata", "customer"]
  },
  {
    id: "map-business-surface",
    categoryId: "environment-understanding",
    journeyStage: "discover",
    title: "Map a business surface from one table",
    description: "Use operational anchors to orient around one known table.",
    template: "Starting from {{sourceTable}}, map the strongest metadata-backed business surfaces around it. Explain which anchors look like governance, scheduling, coordination or execution surfaces without claiming runtime use.",
    parameters: [sourceTableParameter],
    capabilityTool: "dvqr_discover_operational_anchors",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_operational_anchors"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["discover-business-paths", "profile-table"],
    tags: ["environment", "anchors", "business-surface"]
  },
  {
    id: "where-to-start-investigation",
    categoryId: "environment-understanding",
    journeyStage: "understand",
    title: "Suggest where to start investigating",
    description: "Combine bounded capability discovery with an explicit starting-point recommendation.",
    template: "I need to investigate {{problem}}. Show which DVQR capability I should use first, what evidence it can establish, and the safest next prompt. Do not claim the problem's cause.",
    parameters: [{ id: "problem", label: "Problem", description: "Short investigation problem statement.", placeholder: "A related task is missing for a customer record.", required: true }],
    capabilityTool: "dvqr_list_capabilities",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_list_capabilities"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["start-investigation", "search-metadata"],
    tags: ["getting-started", "investigation", "guidance"]
  },
  {
    id: "discover-table-neighborhood",
    categoryId: "environment-understanding",
    journeyStage: "discover",
    title: "Discover a table's business neighborhood",
    description: "Orient around a known table before traversal.",
    template: "For {{sourceTable}}, discover the strongest operational anchors and nearby business capabilities so I can understand its business neighborhood before choosing relationship paths.",
    parameters: [sourceTableParameter],
    capabilityTool: "dvqr_discover_operational_anchors",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_operational_anchors"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["find-relationship-paths", "profile-table"],
    tags: ["environment", "neighborhood", "anchors"]
  },
  {
    id: "find-governance-surfaces",
    categoryId: "environment-understanding",
    journeyStage: "discover",
    title: "Find governance-oriented surfaces",
    description: "Discover governance-oriented anchors without claiming effective security.",
    template: "From {{sourceTable}}, identify metadata-backed governance-oriented operational anchors. Keep governance context separate from effective permissions or security posture.",
    parameters: [sourceTableParameter],
    capabilityTool: "dvqr_discover_operational_anchors",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_operational_anchors"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["inspect-table-metadata", "start-investigation"],
    tags: ["governance", "anchors", "security-boundary"]
  },
  {
    id: "find-execution-surfaces",
    categoryId: "environment-understanding",
    journeyStage: "discover",
    title: "Find execution-oriented surfaces",
    description: "Discover likely execution-oriented anchors before deeper investigation.",
    template: "From {{sourceTable}}, identify metadata-backed execution-oriented operational anchors and explain why they are candidates. Do not claim records or runtime activity exist.",
    parameters: [sourceTableParameter],
    capabilityTool: "dvqr_discover_operational_anchors",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_operational_anchors"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["discover-business-paths", "validate-business-paths"],
    tags: ["execution", "anchors", "runtime-boundary"]
  },
  {
    id: "capability-for-relationship-problem",
    categoryId: "environment-understanding",
    journeyStage: "understand",
    title: "Choose a DVQR path for a relationship problem",
    description: "Guide users from a natural-language relationship problem to the right bounded capability.",
    template: "I need to understand this relationship problem: {{problem}}. Show the DVQR capabilities that can move from metadata-valid paths to runtime validation, in the order I should use them.",
    parameters: [{ id: "problem", label: "Relationship problem", description: "Relationship or missing-related-record problem.", placeholder: "How does a contact reach its tasks?", required: true }],
    capabilityTool: "dvqr_list_capabilities",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_list_capabilities"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["find-relationship-paths", "discover-business-paths"],
    tags: ["capabilities", "relationships", "workflow"]
  },
  {
    id: "capability-for-custom-api-problem",
    categoryId: "environment-understanding",
    journeyStage: "understand",
    title: "Choose a DVQR path for a Custom API problem",
    description: "Guide users through discovery, definition, preview and interpretation.",
    template: "I need to work with a Dataverse Custom API for this goal: {{goal}}. Show the DVQR capabilities I should use from discovery through safe preview and interpretation.",
    parameters: [{ id: "goal", label: "Goal", description: "Custom API goal.", placeholder: "process a service request", required: true }],
    capabilityTool: "dvqr_list_capabilities",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_list_capabilities"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["discover-custom-apis", "recommend-custom-apis"],
    tags: ["capabilities", "custom-api", "workflow"]
  },
  {
    id: "find-table-by-name-fragment",
    categoryId: "metadata-query",
    journeyStage: "discover",
    title: "Find tables by a name fragment",
    description: "Search metadata for likely table matches.",
    template: "Search Dataverse metadata for tables matching {{concept}}. Return logical/display names and explain which matches are strongest without inventing unsupported filters.",
    parameters: [{ id: "concept", label: "Name fragment", description: "Table name or concept fragment.", placeholder: "appointment", required: true }],
    capabilityTool: "dvqr_search_metadata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_search_metadata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["inspect-table-metadata"],
    tags: ["metadata", "search", "table"]
  },
  {
    id: "inspect-table-ownership",
    categoryId: "metadata-query",
    journeyStage: "understand",
    title: "Check a table's ownership model",
    description: "Inspect canonical table metadata for ownership context.",
    template: "For {{table}}, show the metadata-backed ownership model and primary identifiers. Explain the schema facts only; do not infer effective user access.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_entity_metadata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_entity_metadata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-table"],
    tags: ["metadata", "ownership", "security-boundary"]
  },
  {
    id: "inspect-primary-fields",
    categoryId: "metadata-query",
    journeyStage: "understand",
    title: "Find a table's primary fields",
    description: "Retrieve primary ID/name facts before composing queries.",
    template: "For {{table}}, show its primary ID attribute, primary name attribute, entity set name and other identifiers I should know before querying it.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_entity_metadata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_entity_metadata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["run-odata"],
    tags: ["metadata", "primary-id", "entity-set"]
  },
  {
    id: "explain-expand-query",
    categoryId: "metadata-query",
    journeyStage: "understand",
    title: "Explain an OData $expand",
    description: "Explain relationship expansion shape before runtime execution.",
    template: "Explain this Dataverse OData query with special attention to every $expand, navigation property, nested $select and the expected result shape: {{query}}",
    parameters: [{ id: "query", label: "OData query", description: "OData query containing $expand.", placeholder: "contacts?$select=fullname&$expand=parentcustomerid_account($select=name)", required: true }],
    capabilityTool: "dvqr_explain_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_explain_odata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["run-odata", "resolve-navigation-property"],
    tags: ["odata", "expand", "query"]
  },
  {
    id: "explain-filter-query",
    categoryId: "metadata-query",
    journeyStage: "understand",
    title: "Explain an OData filter",
    description: "Explain filtering semantics without executing.",
    template: "Explain exactly what this Dataverse OData $filter does, including boolean grouping and any potentially surprising semantics: {{query}}",
    parameters: [{ id: "query", label: "OData query", description: "OData query containing $filter.", placeholder: "contacts?$filter=statecode eq 0&$top=10", required: true }],
    capabilityTool: "dvqr_explain_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_explain_odata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["run-odata"],
    tags: ["odata", "filter", "query"]
  },
  {
    id: "query-sample-records",
    categoryId: "metadata-query",
    journeyStage: "query",
    title: "Get a small sample of records",
    description: "Run a bounded read-only sample query.",
    template: "Run this bounded read-only Dataverse OData query and show a concise sample of returned rows: {{query}}",
    parameters: [{ id: "query", label: "OData query", description: "Bounded OData GET path.", placeholder: "contacts?$select=contactid,fullname&$top=5", required: true }],
    capabilityTool: "dvqr_execute_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_execute_odata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["explain-odata", "find-relationship-paths"],
    tags: ["odata", "sample", "read-only"]
  },
  {
    id: "verify-query-returns-rows",
    categoryId: "metadata-query",
    journeyStage: "verify",
    title: "Check whether a query returns rows",
    description: "Use bounded runtime evidence to distinguish valid query shape from actual returned data.",
    template: "Run this bounded read-only query and tell me whether it returns rows. Keep 'valid query' separate from 'data exists': {{query}}",
    parameters: [{ id: "query", label: "OData query", description: "Bounded OData GET path.", placeholder: "accounts?$select=accountid,name&$top=5", required: true }],
    capabilityTool: "dvqr_execute_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_execute_odata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["explain-odata"],
    tags: ["odata", "runtime", "rows"]
  },
  {
    id: "inspect-table-before-query",
    categoryId: "metadata-query",
    journeyStage: "understand",
    title: "Inspect schema before writing a query",
    description: "Use metadata first to reduce guessed query construction.",
    template: "Before I query {{table}}, show the metadata facts most relevant to constructing a safe bounded OData read: entity set, primary fields, ownership and useful schema identifiers.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_entity_metadata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_entity_metadata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["run-odata", "resolve-navigation-property"],
    tags: ["metadata", "query-planning", "schema"]
  },
  {
    id: "explain-generated-relationship-query",
    categoryId: "metadata-query",
    journeyStage: "verify",
    title: "Explain a generated relationship query",
    description: "Review generated OData before running it.",
    template: "Explain this generated Dataverse relationship query and identify its source table, navigation path, selected columns, filters and bounds before I execute it: {{query}}",
    parameters: [{ id: "query", label: "Generated OData query", description: "Relationship OData query to review.", placeholder: "contacts(<id>)?$expand=...", required: true }],
    capabilityTool: "dvqr_explain_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_explain_odata"],
    prerequisitePromptIds: ["generate-relationship-query"],
    followUpPromptIds: ["run-odata"],
    tags: ["odata", "relationship", "verify"]
  },
  {
    id: "bounded-query-for-known-table",
    categoryId: "metadata-query",
    journeyStage: "query",
    title: "Run a known-table query safely",
    description: "Execute an explicit bounded GET and summarize only observed rows.",
    template: "For {{table}}, run this explicit bounded read-only OData GET and summarize only what is observed: {{query}}",
    parameters: [tableParameter, { id: "query", label: "OData query", description: "Explicit bounded GET path.", placeholder: "accounts?$select=accountid,name&$top=10", required: true }],
    capabilityTool: "dvqr_execute_odata",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_execute_odata"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-table"],
    tags: ["odata", "bounded", "read-only"]
  },
  {
    id: "how-are-tables-related",
    categoryId: "relationships-traversal",
    journeyStage: "navigate",
    title: "How are two tables related?",
    description: "Find metadata-valid routes without claiming data viability.",
    template: "How can {{sourceTable}} reach {{targetTable}} in Dataverse metadata? Show the strongest bounded relationship paths and clearly separate metadata reachability from runtime viability.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_find_relationship_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_find_relationship_paths"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["probe-relationship-path", "discover-business-paths"],
    tags: ["relationships", "paths", "metadata"]
  },
  {
    id: "shortest-relationship-path",
    categoryId: "relationships-traversal",
    journeyStage: "navigate",
    title: "Find the shortest relationship route",
    description: "Prefer concise metadata-valid routes while preserving alternatives.",
    template: "Find the shortest metadata-valid relationship path from {{sourceTable}} to {{targetTable}}, plus a small number of useful alternatives. Do not claim any path returns rows.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_find_relationship_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_find_relationship_paths"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["probe-relationship-path"],
    tags: ["relationships", "shortest-path", "metadata"]
  },
  {
    id: "compare-business-path-candidates",
    categoryId: "relationships-traversal",
    journeyStage: "understand",
    title: "Compare candidate business paths",
    description: "Explain why ranked candidate routes differ.",
    template: "Discover and compare likely business paths from {{sourceTable}} to {{targetTable}}. Explain why the candidates rank differently while keeping metadata validity separate from runtime viability and business preference.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_discover_business_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_business_paths"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["validate-business-paths"],
    tags: ["business-path", "compare", "ranking"]
  },
  {
    id: "validate-path-from-record",
    categoryId: "relationships-traversal",
    journeyStage: "verify",
    title: "Test paths from a real record",
    description: "Validate candidate paths hop-by-hop from one source record.",
    template: "Starting from {{sourceTable}} record {{recordId}}, validate candidate routes to {{targetTable}} and show row counts at each hop, including the exact hop where any branch becomes empty.",
    parameters: [sourceTableParameter, recordIdParameter, targetTableParameter],
    capabilityTool: "dvqr_validate_business_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_validate_business_paths"],
    prerequisitePromptIds: ["discover-business-paths"],
    followUpPromptIds: ["generate-relationship-query"],
    tags: ["business-path", "record", "runtime"]
  },
  {
    id: "why-path-empty",
    categoryId: "relationships-traversal",
    journeyStage: "verify",
    title: "Find where a relationship path becomes empty",
    description: "Probe runtime reachability without turning emptiness into root cause.",
    template: "From {{sourceTable}} record {{recordId}} toward {{targetTable}}, probe the selected relationship route and identify the first hop that returns no rows. Treat that as observed reachability evidence, not root cause.",
    parameters: [sourceTableParameter, recordIdParameter, targetTableParameter],
    capabilityTool: "dvqr_probe_relationship_path",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_probe_relationship_path"],
    prerequisitePromptIds: ["find-relationship-paths"],
    followUpPromptIds: ["start-investigation"],
    tags: ["relationship", "empty", "runtime"]
  },
  {
    id: "lookup-targets",
    categoryId: "relationships-traversal",
    journeyStage: "understand",
    title: "Show the valid targets of a lookup",
    description: "Explain lookup targets and polymorphism from metadata.",
    template: "For lookup {{lookup}} on {{table}}, show all metadata-backed target tables and whether the lookup is polymorphic. Do not guess a navigation property.",
    parameters: [tableParameter, { id: "lookup", label: "Lookup", description: "Lookup logical name.", placeholder: "customerid", required: true }],
    capabilityTool: "dvqr_explain_lookup",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_explain_lookup"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["resolve-navigation-property"],
    tags: ["lookup", "polymorphic", "targets"]
  },
  {
    id: "verify-navigation-guess",
    categoryId: "relationships-traversal",
    journeyStage: "verify",
    title: "Verify my navigation-property guess",
    description: "Check a guessed navigation name against metadata.",
    template: "On {{sourceTable}}, verify whether {{guessedProperty}} is the correct navigation property toward {{targetTable}}. If not, return metadata-backed alternatives only.",
    parameters: [sourceTableParameter, targetTableParameter, { id: "guessedProperty", label: "Guessed property", description: "Navigation property to verify.", placeholder: "primarycontactid", required: true }],
    capabilityTool: "dvqr_resolve_navigation_property",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_resolve_navigation_property"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["generate-relationship-query"],
    tags: ["navigation-property", "verify", "metadata"]
  },
  {
    id: "generate-expand-from-path",
    categoryId: "relationships-traversal",
    journeyStage: "query",
    title: "Generate OData for a verified path",
    description: "Turn a verified relationship route into bounded OData.",
    template: "Generate a bounded OData query from {{sourceTable}} to {{targetTable}} using only a metadata-verified relationship path, with a focused $select and no invented navigation properties.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_generate_relationship_query",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_generate_relationship_query"],
    prerequisitePromptIds: ["find-relationship-paths"],
    followUpPromptIds: ["explain-generated-relationship-query", "run-odata"],
    tags: ["relationship", "odata", "expand"]
  },
  {
    id: "find-alternate-path",
    categoryId: "relationships-traversal",
    journeyStage: "navigate",
    title: "Find an alternate route between tables",
    description: "Look beyond one obvious route while staying metadata-backed.",
    template: "Find alternative metadata-valid paths from {{sourceTable}} to {{targetTable}} beyond the most obvious direct route. Rank a bounded set and explain the trade-offs without claiming runtime data exists.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_find_relationship_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_find_relationship_paths"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["validate-business-paths"],
    tags: ["relationship", "alternate-path", "metadata"]
  },
  {
    id: "business-path-before-query",
    categoryId: "relationships-traversal",
    journeyStage: "navigate",
    title: "Choose a business path before querying",
    description: "Use ranked path intelligence before generating OData.",
    template: "Before generating a query from {{sourceTable}} to {{targetTable}}, discover the strongest candidate business paths and tell me which ones still need runtime validation.",
    parameters: [sourceTableParameter, targetTableParameter],
    capabilityTool: "dvqr_discover_business_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_business_paths"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["validate-business-paths", "generate-relationship-query"],
    tags: ["business-path", "query-planning", "ranking"]
  },
  {
    id: "metadata-vs-runtime-path",
    categoryId: "relationships-traversal",
    journeyStage: "verify",
    title: "Compare metadata-valid and runtime-viable paths",
    description: "Teach the distinction between relationship existence and populated routes.",
    template: "For {{sourceTable}} record {{recordId}} reaching {{targetTable}}, compare metadata-valid candidate paths with the paths that actually return rows at runtime. Show empty branches explicitly.",
    parameters: [sourceTableParameter, recordIdParameter, targetTableParameter],
    capabilityTool: "dvqr_validate_business_paths",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_validate_business_paths"],
    prerequisitePromptIds: ["discover-business-paths"],
    followUpPromptIds: ["start-investigation"],
    tags: ["relationship", "metadata-vs-runtime", "viability"]
  },
  {
    id: "find-api-by-purpose",
    categoryId: "custom-apis",
    journeyStage: "discover",
    title: "Find a Custom API by purpose",
    description: "Search public APIs for a natural-language goal.",
    template: "Find public Dataverse Custom APIs that could support this purpose: {{goal}}. Rank metadata-backed matches and return no strong fit rather than guessing.",
    parameters: [{ id: "goal", label: "Purpose", description: "Desired API purpose.", placeholder: "validate a service request", required: true }],
    capabilityTool: "dvqr_discover_custom_apis",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_discover_custom_apis"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["explain-custom-api", "get-custom-api-definition"],
    tags: ["custom-api", "purpose", "discover"]
  },
  {
    id: "inspect-api-inputs-outputs",
    categoryId: "custom-apis",
    journeyStage: "understand",
    title: "Inspect Custom API inputs and outputs",
    description: "Retrieve exact parameter and response metadata.",
    template: "For {{apiName}}, show the exact request parameters and response properties, including types, requiredness and binding context from metadata.",
    parameters: [apiParameter],
    capabilityTool: "dvqr_get_custom_api_definition",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_custom_api_definition"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["check-custom-api-readiness"],
    tags: ["custom-api", "parameters", "metadata"]
  },
  {
    id: "compare-api-fit",
    categoryId: "custom-apis",
    journeyStage: "understand",
    title: "Compare APIs for one business goal",
    description: "Compare exact named APIs against one goal.",
    template: "For this goal — {{goal}} — compare these exact Custom APIs: {{apiNames}}. Explain metadata-backed strengths and limitations without inventing capabilities.",
    parameters: [{ id: "goal", label: "Goal", description: "Business goal to compare against.", placeholder: "process an incoming request", required: true }, { id: "apiNames", label: "Custom APIs", description: "Comma-separated exact API names.", placeholder: "contoso_Process, contoso_Validate", required: true }],
    capabilityTool: "dvqr_compare_custom_apis",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_compare_custom_apis"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["recommend-solution-architecture"],
    tags: ["custom-api", "compare", "fit"]
  },
  {
    id: "preview-api-with-parameters",
    categoryId: "custom-apis",
    journeyStage: "verify",
    title: "Preview an API call with parameters",
    description: "Build a non-executing invocation preview.",
    template: "For {{apiName}}, preview the invocation using {{parameters}}. Show the exact call shape, binding and validation warnings, but do not execute it.",
    parameters: [apiParameter, { id: "parameters", label: "Parameters", description: "Proposed parameter values.", placeholder: "Text='hello', Mode='draft'", required: true }],
    capabilityTool: "dvqr_preview_custom_api_execution",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_preview_custom_api_execution"],
    prerequisitePromptIds: ["get-custom-api-definition"],
    followUpPromptIds: ["check-custom-api-readiness"],
    tags: ["custom-api", "preview", "parameters"]
  },
  {
    id: "explain-api-readiness-blockers",
    categoryId: "custom-apis",
    journeyStage: "verify",
    title: "Explain Custom API readiness blockers",
    description: "Use metadata-only checks to explain why a proposed call is not ready.",
    template: "Check {{apiName}} with {{parameters}} and explain every metadata-backed blocker or warning that prevents a safe invocation. Do not execute it.",
    parameters: [apiParameter, { id: "parameters", label: "Parameters", description: "Proposed parameter values.", placeholder: "Text='hello'", required: true }],
    capabilityTool: "dvqr_check_custom_api_execution",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_check_custom_api_execution"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["get-custom-api-definition", "preview-custom-api"],
    tags: ["custom-api", "readiness", "blockers"]
  },
  {
    id: "summarize-last-api-execution",
    categoryId: "custom-apis",
    journeyStage: "verify",
    title: "Summarize the last Custom API execution",
    description: "Interpret stored execution evidence without rerunning.",
    template: "Summarize the most recent stored Custom API execution evidence: operation, outcome, returned outputs or failure classification, and bounded next steps. Do not execute again.",
    parameters: [],
    capabilityTool: "dvqr_interpret_custom_api_execution",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_interpret_custom_api_execution"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["get-custom-api-definition"],
    tags: ["custom-api", "execution", "summary"]
  },
  {
    id: "profile-explain-score",
    categoryId: "operational-profile",
    journeyStage: "understand",
    title: "Explain why this table received its score",
    description: "Break down canonical weighted evidence and calibration.",
    template: "Get the live Operational Profile for {{table}} and explain why it received its DVQR Score. Show each weighted contributor, maximum contribution, weighted-evidence total and calibration without inventing residual points.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-score-boundaries"],
    tags: ["operational-profile", "score", "explain"]
  },
  {
    id: "profile-biggest-contributors",
    categoryId: "operational-profile",
    journeyStage: "understand",
    title: "Show the biggest DVQR Score contributors",
    description: "Rank observed contributors without converting them into risk.",
    template: "For {{table}}, show the largest Operational Profile score contributors in descending order and explain what each observed evidence dimension means. Do not reinterpret them as risk or health.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-score-boundaries"],
    tags: ["operational-profile", "contributors", "ranking"]
  },
  {
    id: "profile-investigate-first",
    categoryId: "operational-profile",
    journeyStage: "investigate",
    title: "What should I investigate first?",
    description: "Use the profile as orientation, not root-cause proof.",
    template: "Get the live Operational Profile for {{table}} and suggest which observed operational surfaces are worth investigating first. Base suggestions on evidence density only and do not claim root cause.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["start-investigation", "find-relationship-paths"],
    tags: ["operational-profile", "investigation", "orientation"]
  },
  {
    id: "profile-relationship-contribution",
    categoryId: "operational-profile",
    journeyStage: "understand",
    title: "Explain the relationship contribution",
    description: "Interpret relationship fanout without claiming viable paths.",
    template: "For {{table}}, explain the Broad Relationship Surface contribution to the DVQR Score. State the observed relationship count and weighted points, and explain why this does not prove runtime-viable, preferred or access paths.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["find-relationship-paths"],
    tags: ["operational-profile", "relationships", "guardrail"]
  },
  {
    id: "profile-plugin-contribution",
    categoryId: "operational-profile",
    journeyStage: "understand",
    title: "Explain plug-in participation",
    description: "Interpret synchronous plug-in-step evidence precisely.",
    template: "For {{table}}, explain the Heavy Runtime Participation contribution. Use the exact synchronous plug-in-step evidence and do not turn step count into distinct plug-ins, performance impact or causality.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["start-investigation"],
    tags: ["operational-profile", "plugins", "guardrail"]
  },
  {
    id: "profile-orchestration-contribution",
    categoryId: "operational-profile",
    journeyStage: "understand",
    title: "Explain orchestration participation",
    description: "Interpret workflow/flow participation without guessing execution mode.",
    template: "For {{table}}, explain the Significant Orchestration Density contribution. Keep workflow/flow participation separate from assumptions about asynchronous execution, delays, bypassed controls or causality.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["start-investigation"],
    tags: ["operational-profile", "orchestration", "guardrail"]
  },
  {
    id: "profile-unknown-evidence",
    categoryId: "operational-profile",
    journeyStage: "verify",
    title: "Show unavailable or unknown profile evidence",
    description: "Keep missing/unavailable evidence distinct from observed zero.",
    template: "For {{table}}, show which Operational Profile evidence is observed, zero, unavailable or unknown. Do not treat unavailable evidence as zero.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-explain-score"],
    tags: ["operational-profile", "unknown", "evidence"]
  },
  {
    id: "profile-current-vs-snapshot",
    categoryId: "operational-profile",
    journeyStage: "verify",
    title: "Use the live profile instead of an old snapshot",
    description: "Reinforce current-request source authority.",
    template: "Get the current live Operational Profile for {{table}}. If older DVQR snapshots exist, treat them as historical evidence only and do not substitute them for the live current-request result.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: [],
    followUpPromptIds: ["profile-explain-score"],
    tags: ["operational-profile", "live", "snapshot"]
  },
  {
    id: "profile-performance-boundary",
    categoryId: "operational-profile",
    journeyStage: "verify",
    title: "Does this score prove a performance problem?",
    description: "Test the performance interpretation boundary.",
    template: "For {{table}}, does its DVQR Score prove that saves, reads or other operations are slow? Explain exactly what the Operational Profile can and cannot establish about performance.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: ["profile-table"],
    followUpPromptIds: ["start-investigation"],
    tags: ["operational-profile", "performance", "guardrail"]
  },
  {
    id: "profile-security-boundary",
    categoryId: "operational-profile",
    journeyStage: "verify",
    title: "Does this score prove a security problem?",
    description: "Test the security interpretation boundary.",
    template: "For {{table}}, does its DVQR Score or relationship/ownership evidence prove a security weakness or effective access path? Explain the canonical boundary.",
    parameters: [tableParameter],
    capabilityTool: "dvqr_get_operational_profile",
    tier: "free",
    evidenceMatrixRefs: ["tool:dvqr_get_operational_profile"],
    prerequisitePromptIds: ["profile-table"],
    followUpPromptIds: ["start-investigation"],
    tags: ["operational-profile", "security", "guardrail"]
  },
  {
    id: "investigation-current-question",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "Show the investigation's current question",
    description: "Read persisted intent without reconstructing from chat.",
    template: "For investigation {{investigationId}}, show the persisted problem statement and current investigation intent. Do not infer a different question from conversation history.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-investigation-strategy"],
    tags: ["investigation", "intent", "state"]
  },
  {
    id: "investigation-next-step",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "What is the next investigation step?",
    description: "Read the persisted strategy without advancing it.",
    template: "For investigation {{investigationId}}, show the single current canonical strategy step and why it is next. Do not advance or acquire evidence.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_investigation_strategy",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_investigation_strategy"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["continue-investigation", "acquire-recommended-evidence"],
    tags: ["investigation", "next-step", "strategy"]
  },
  {
    id: "investigation-evidence-so-far",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "What evidence do we have so far?",
    description: "Review persisted evidence without recollection.",
    template: "For investigation {{investigationId}}, summarize the persisted evidence collected so far by provider and evidence state. Keep observed, missing and unavailable evidence distinct.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_list_investigation_evidence",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_list_investigation_evidence"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-readiness", "summarize-investigation"],
    tags: ["investigation", "evidence", "status"]
  },
  {
    id: "investigation-one-step-only",
    categoryId: "managed-investigation",
    journeyStage: "investigate",
    title: "Advance exactly one investigation step",
    description: "Enforce the one-step managed-investigation boundary.",
    template: "Advance investigation {{investigationId}} by exactly one canonical strategy step, persist the result, and stop. Do not chain another provider or Mini RCA action.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_continue_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_continue_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-investigation-state"],
    tags: ["investigation", "bounded", "continue"]
  },
  {
    id: "investigation-acquire-next-evidence",
    categoryId: "managed-investigation",
    journeyStage: "investigate",
    title: "Collect the next recommended evidence",
    description: "Acquire exactly the persisted recommendation.",
    template: "For investigation {{investigationId}}, collect exactly the currently recommended evidence item using the persisted provider/action token, reconcile the strategy, and stop after that one acquisition.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_acquire_investigation_evidence",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_acquire_investigation_evidence"],
    prerequisitePromptIds: ["show-investigation-strategy"],
    followUpPromptIds: ["list-investigation-evidence", "show-readiness"],
    tags: ["investigation", "evidence", "bounded"]
  },
  {
    id: "investigation-readiness-why",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Why is this investigation ready or not ready?",
    description: "Explain canonical readiness from current evidence only.",
    template: "Assess investigation {{investigationId}} and explain why its current evidence makes it ready or not ready for a Mini RCA checkpoint. Do not acquire new evidence.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_assess_investigation_readiness",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_assess_investigation_readiness"],
    prerequisitePromptIds: ["list-investigation-evidence"],
    followUpPromptIds: ["get-mini-rca", "acquire-recommended-evidence"],
    tags: ["investigation", "readiness", "explain"]
  },
  {
    id: "investigation-before-mini-rca",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Check before generating Mini RCA",
    description: "Use readiness as the gate before hypothesis checkpoint generation.",
    template: "Before generating Mini RCA for investigation {{investigationId}}, assess current readiness and identify unresolved evidence gaps. Do not generate the checkpoint yet.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_assess_investigation_readiness",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_assess_investigation_readiness"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["get-mini-rca"],
    tags: ["investigation", "mini-rca", "readiness"]
  },
  {
    id: "investigation-mini-rca-supported",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Show supported Mini RCA hypotheses",
    description: "Read the persisted checkpoint without overstating certainty.",
    template: "For investigation {{investigationId}}, show the latest persisted Mini RCA checkpoint and focus on supported hypotheses, citing the persisted evidence that supports them. Do not call any hypothesis proven root cause.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_mini_rca",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_mini_rca"],
    prerequisitePromptIds: ["get-mini-rca"],
    followUpPromptIds: ["summarize-investigation"],
    tags: ["investigation", "mini-rca", "supported"]
  },
  {
    id: "investigation-mini-rca-unresolved",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Show unresolved Mini RCA hypotheses",
    description: "Surface uncertainty and missing evidence from the persisted checkpoint.",
    template: "For investigation {{investigationId}}, show unresolved hypotheses in the latest persisted Mini RCA checkpoint and what evidence remains missing or inconclusive. Do not regenerate it.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_mini_rca",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_mini_rca"],
    prerequisitePromptIds: ["get-mini-rca"],
    followUpPromptIds: ["show-investigation-strategy", "acquire-recommended-evidence"],
    tags: ["investigation", "mini-rca", "unresolved"]
  },
  {
    id: "investigation-handoff-summary",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "Prepare an investigation handoff summary",
    description: "Summarize persisted state for another investigator.",
    template: "Prepare a concise handoff summary for investigation {{investigationId}} from persisted DVQR state: question, intent, evidence, completed/current strategy, readiness, Mini RCA status and unresolved gaps. Do not collect anything new.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_summarize_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_summarize_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-investigation-state"],
    tags: ["investigation", "handoff", "summary"]
  },
  {
    id: "investigation-resume-context",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "Reorient me to an existing investigation",
    description: "Reload authoritative state after time away.",
    template: "Reorient me to investigation {{investigationId}} using only persisted DVQR state. Tell me what was being investigated, what evidence exists, where the strategy stopped and the next bounded action.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_summarize_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_summarize_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-investigation-strategy", "continue-investigation"],
    tags: ["investigation", "resume", "context"]
  },
  {
    id: "investigation-no-conversation-memory",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Rebuild nothing from conversation memory",
    description: "Verify persisted-state authority.",
    template: "For investigation {{investigationId}}, show the authoritative persisted investigation state and explicitly avoid reconstructing missing facts from conversation memory.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_investigation",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_investigation"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["list-investigation-evidence"],
    tags: ["investigation", "persistence", "authority"]
  },
  {
    id: "investigation-evidence-without-recollect",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Review evidence without recollecting it",
    description: "Ensure evidence inspection remains read-only.",
    template: "List and summarize persisted evidence for investigation {{investigationId}} without recollecting, refreshing or replacing any provider result.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_list_investigation_evidence",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_list_investigation_evidence"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["show-readiness"],
    tags: ["investigation", "evidence", "read-only"]
  },
  {
    id: "investigation-strategy-progress",
    categoryId: "managed-investigation",
    journeyStage: "understand",
    title: "Show investigation strategy progress",
    description: "Separate completed, current and future strategy steps.",
    template: "For investigation {{investigationId}}, show completed strategy steps, the current step and upcoming bounded steps. Explain progress without advancing anything.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_investigation_strategy",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_investigation_strategy"],
    prerequisitePromptIds: ["start-investigation"],
    followUpPromptIds: ["continue-investigation"],
    tags: ["investigation", "strategy", "progress"]
  },
  {
    id: "investigation-mini-rca-boundary",
    categoryId: "managed-investigation",
    journeyStage: "verify",
    title: "Explain what Mini RCA does not prove",
    description: "Reinforce bounded hypothesis semantics.",
    template: "For investigation {{investigationId}}, read the latest Mini RCA checkpoint and explain why it is an evidence-backed hypothesis checkpoint rather than proof of root cause. Keep supported, weakened and unresolved hypotheses distinct.",
    parameters: [investigationParameter],
    capabilityTool: "dvqr_get_mini_rca",
    tier: "pro",
    evidenceMatrixRefs: ["tool:dvqr_get_mini_rca"],
    prerequisitePromptIds: ["get-mini-rca"],
    followUpPromptIds: ["summarize-investigation"],
    tags: ["investigation", "mini-rca", "guardrail"]
  }
];
