import * as assert from "node:assert";
import { rootEntitySetFromODataQuery } from "../../mcp/mcpODataPath.js";

suite("mcpODataPath", () => {
  test("recognises a collection query", () => {
    assert.strictEqual(rootEntitySetFromODataQuery("contacts?$select=fullname&$top=5"), "contacts");
  });

  test("recognises a record-navigation query generated by relationship intelligence", () => {
    assert.strictEqual(
      rootEntitySetFromODataQuery("contacts(53992a59-4abb-4834-afe0-00078e7352b7)/Contact_Tasks?$select=activityid,subject&$top=5"),
      "contacts"
    );
  });

  test("recognises an absolute Dataverse Web API query", () => {
    assert.strictEqual(
      rootEntitySetFromODataQuery("https://example.crm6.dynamics.com/api/data/v9.2/contacts(abc)/Contact_Tasks"),
      "contacts"
    );
  });

  test("rejects a query without a root entity set", () => {
    assert.strictEqual(rootEntitySetFromODataQuery("?$select=fullname"), undefined);
  });
});
